// GENERATED by scripts/sync-starcg-data.mjs — do not edit by hand.
//
// Source: github.com/dalindev/StarCG (fork of wodenchen/StarCG), data version 20260802,
// which cites https://guide.starcg.net/equipment/ as its own origin.
// Re-run the script after merging upstream to pick up new game data.
//
// 421 equipment entries (420 flat, 1 with per-itemId variants),
// 385 with per-stat [min, max] ranges, 385 with a level.

/** market.php ITEM_MODIFY* field names that carry a rollable equipment stat. */
export type EquipmentStatKey = keyof typeof EQUIPMENT_STAT_LABELS;

export const EQUIPMENT_STAT_LABELS = {
  "ITEM_MODIFYAGILITY": "敏捷",
  "ITEM_MODIFYHP": "生命",
  "ITEM_MODIFYAVOID": "閃躲",
  "ITEM_MODIFYDEFENCE": "防禦",
  "ITEM_ADM": "魔攻",
  "ITEM_MODIFYCRITICAL": "必殺",
  "ITEM_MODIFYRECOVERY": "回復",
  "ITEM_MODIFYCOUNTER": "反擊",
  "ITEM_MODIFYHITRATE": "命中",
  "ITEM_MODIFYFORCEPOINT": "魔力",
  "ITEM_MODIFYMAGIC": "精神",
  "ITEM_RSS": "魔抗",
  "ITEM_MODIFYATTACK": "攻擊"
} as const;

/** Highest value a stat normally rolls at. A listing ABOVE this is a 破頂 (over-cap) item. */
export const EQUIPMENT_MAX_STATS: Record<string, Record<string, number> | { byItemId: Record<string, Record<string, number>> }> = {
  "長劍": {
    "ITEM_MODIFYATTACK": 24
  },
  "闊劍": {
    "ITEM_MODIFYATTACK": 36
  },
  "突刺劍": {
    "ITEM_MODIFYATTACK": 48
  },
  "火舌劍": {
    "ITEM_MODIFYATTACK": 60
  },
  "面包劍": {
    "ITEM_MODIFYATTACK": 72
  },
  "雙手劍": {
    "ITEM_MODIFYATTACK": 84
  },
  "雙刃長劍": {
    "ITEM_MODIFYATTACK": 96
  },
  "鎖刃劍": {
    "ITEM_MODIFYATTACK": 108
  },
  "格斗劍": {
    "ITEM_MODIFYATTACK": 120
  },
  "長鍔劍": {
    "ITEM_MODIFYATTACK": 132
  },
  "黑作太刀": {
    "ITEM_MODIFYATTACK": 129,
    "ITEM_MODIFYAGILITY": 5
  },
  "豬牙劍": {
    "ITEM_MODIFYATTACK": 144
  },
  "雙刃闊劍": {
    "ITEM_MODIFYATTACK": 156
  },
  "巨劍": {
    "ITEM_MODIFYATTACK": 170,
    "ITEM_MODIFYHITRATE": 12
  },
  "長軍刀": {
    "ITEM_MODIFYATTACK": 180
  },
  "護身短劍": {
    "ITEM_MODIFYATTACK": 230
  },
  "細柄短劍": {
    "ITEM_MODIFYATTACK": 204
  },
  "長軍刀+": {
    "ITEM_MODIFYATTACK": 180,
    "ITEM_MODIFYCRITICAL": 2
  },
  "村正": {},
  "細刃重劍": {
    "ITEM_MODIFYATTACK": 228
  },
  "剛硬巨劍": {},
  "青龍刀": {
    "ITEM_MODIFYATTACK": 240
  },
  "曲刀": {
    "ITEM_MODIFYHITRATE": 3,
    "ITEM_MODIFYAVOID": 3
  },
  "彎勾劍": {
    "ITEM_MODIFYATTACK": 250,
    "ITEM_MODIFYHITRATE": 7
  },
  "剛毅": {
    "ITEM_MODIFYATTACK": 300,
    "ITEM_MODIFYAVOID": 22
  },
  "手斧": {
    "ITEM_MODIFYATTACK": 29,
    "ITEM_MODIFYCRITICAL": 20
  },
  "勇氣之斧": {
    "ITEM_MODIFYATTACK": 44,
    "ITEM_MODIFYCRITICAL": 20
  },
  "寬手斧": {
    "ITEM_MODIFYATTACK": 58,
    "ITEM_MODIFYCRITICAL": 20
  },
  "戰斗手斧": {
    "ITEM_MODIFYATTACK": 73,
    "ITEM_MODIFYCRITICAL": 20
  },
  "格斗手斧": {
    "ITEM_MODIFYATTACK": 87,
    "ITEM_MODIFYCRITICAL": 20
  },
  "鋼斧": {
    "ITEM_MODIFYATTACK": 102,
    "ITEM_MODIFYCRITICAL": 20
  },
  "長戰斧": {
    "ITEM_MODIFYATTACK": 116,
    "ITEM_MODIFYCRITICAL": 20
  },
  "雙刃斧": {
    "ITEM_MODIFYATTACK": 131,
    "ITEM_MODIFYCRITICAL": 20
  },
  "鈎爪斧": {
    "ITEM_MODIFYATTACK": 145,
    "ITEM_MODIFYCRITICAL": 20
  },
  "闊刃斧": {
    "ITEM_MODIFYATTACK": 160,
    "ITEM_MODIFYCRITICAL": 20
  },
  "鑽保雷格之斧": {
    "ITEM_MODIFYATTACK": 169,
    "ITEM_MODIFYCOUNTER": 4
  },
  "彎月大戰斧": {
    "ITEM_MODIFYATTACK": 174,
    "ITEM_MODIFYCRITICAL": 20
  },
  "大型闊刃斧": {
    "ITEM_MODIFYATTACK": 189,
    "ITEM_MODIFYCRITICAL": 20
  },
  "大型雙刃斧": {
    "ITEM_MODIFYATTACK": 218,
    "ITEM_MODIFYCRITICAL": 20
  },
  "超大皇帝斧": {
    "ITEM_MODIFYATTACK": 145,
    "ITEM_MODIFYCRITICAL": 38
  },
  "新月斧": {
    "ITEM_MODIFYATTACK": 232,
    "ITEM_MODIFYCRITICAL": 20
  },
  "米諾陶斯戰斧": {
    "ITEM_MODIFYATTACK": 245,
    "ITEM_MODIFYCRITICAL": 20
  },
  "大型雙刃斧+": {
    "ITEM_MODIFYATTACK": 225,
    "ITEM_MODIFYCRITICAL": 20,
    "ITEM_MODIFYCOUNTER": 5
  },
  "帕魯凱斯之斧": {},
  "薄刃鈎爪斧": {
    "ITEM_MODIFYATTACK": 276,
    "ITEM_MODIFYCRITICAL": 20
  },
  "彎月長柄斧": {
    "ITEM_MODIFYATTACK": 276,
    "ITEM_MODIFYCRITICAL": 23
  },
  "金屬重斧": {
    "ITEM_MODIFYATTACK": 305,
    "ITEM_MODIFYCRITICAL": 20
  },
  "處刑斧": {
    "ITEM_MODIFYATTACK": 310,
    "ITEM_MODIFYCRITICAL": 20
  },
  "高速斧": {
    "ITEM_MODIFYATTACK": 312,
    "ITEM_MODIFYCRITICAL": 14
  },
  "重擊斧": {
    "ITEM_MODIFYATTACK": 379,
    "ITEM_MODIFYCRITICAL": 38
  },
  "短矛": {
    "ITEM_MODIFYATTACK": 20,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "攻城槍": {
    "ITEM_MODIFYATTACK": 30,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "刺槍": {
    "ITEM_MODIFYATTACK": 40,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "金屬槍": {
    "ITEM_MODIFYATTACK": 50,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "長柄彎槍": {
    "ITEM_MODIFYATTACK": 60,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "長柄尖槍": {
    "ITEM_MODIFYATTACK": 70,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "穗槍": {
    "ITEM_MODIFYATTACK": 80,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "雙叉戟": {
    "ITEM_MODIFYATTACK": 90,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "護衛槍": {
    "ITEM_MODIFYATTACK": 100,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "騎士槍": {
    "ITEM_MODIFYATTACK": 110,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "偃月刀": {
    "ITEM_MODIFYATTACK": 118,
    "ITEM_MODIFYDEFENCE": 4
  },
  "大砍槍": {
    "ITEM_MODIFYATTACK": 120,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "長尖槍": {
    "ITEM_MODIFYATTACK": 130,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "蠍槍": {
    "ITEM_MODIFYATTACK": 140,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "雙刃槍": {
    "ITEM_MODIFYATTACK": 125,
    "ITEM_MODIFYHITRATE": 8,
    "ITEM_MODIFYCOUNTER": 14
  },
  "闊刃槍": {
    "ITEM_MODIFYATTACK": 160,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "東方長刺鎗": {
    "ITEM_MODIFYHITRATE": 10,
    "ITEM_MODIFYCOUNTER": 8
  },
  "蠍槍+": {
    "ITEM_MODIFYATTACK": 148,
    "ITEM_MODIFYHITRATE": 7,
    "ITEM_MODIFYCOUNTER": 9
  },
  "天空之槍": {},
  "鈎爪槍": {
    "ITEM_MODIFYATTACK": 190,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "原始槍": {
    "ITEM_MODIFYATTACK": 190,
    "ITEM_MODIFYHITRATE": 7,
    "ITEM_MODIFYCOUNTER": 11
  },
  "三叉戰戟": {
    "ITEM_MODIFYATTACK": 210,
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYCOUNTER": 8
  },
  "異型槍": {
    "ITEM_MODIFYHITRATE": 3,
    "ITEM_MODIFYCOUNTER": 3
  },
  "痛擊槍": {
    "ITEM_MODIFYATTACK": 230,
    "ITEM_MODIFYCRITICAL": 10,
    "ITEM_MODIFYCOUNTER": 10
  },
  "穿刺槍": {
    "ITEM_MODIFYATTACK": 250,
    "ITEM_MODIFYHITRATE": 18
  },
  "輕型弓": {
    "ITEM_MODIFYATTACK": 22
  },
  "威力短弓": {
    "ITEM_MODIFYATTACK": 33
  },
  "短戰弓": {
    "ITEM_MODIFYATTACK": 44
  },
  "獵弓": {
    "ITEM_MODIFYATTACK": 55
  },
  "強弓": {
    "ITEM_MODIFYATTACK": 66
  },
  "格斗弓": {
    "ITEM_MODIFYATTACK": 77
  },
  "狙擊弓": {
    "ITEM_MODIFYATTACK": 88
  },
  "超強狙擊弓": {
    "ITEM_MODIFYATTACK": 99
  },
  "殺手長弓": {
    "ITEM_MODIFYATTACK": 110
  },
  "沖擊弓": {
    "ITEM_MODIFYATTACK": 121
  },
  "米斯特汀之弓": {
    "ITEM_MODIFYATTACK": 123,
    "ITEM_MODIFYAVOID": 3
  },
  "巨弓": {
    "ITEM_MODIFYATTACK": 132
  },
  "長格斗弓": {
    "ITEM_MODIFYATTACK": 143
  },
  "破邪長弓": {
    "ITEM_MODIFYATTACK": 130,
    "ITEM_MODIFYCRITICAL": 4,
    "ITEM_MODIFYHITRATE": 12
  },
  "月光長弓": {
    "ITEM_MODIFYATTACK": 165
  },
  "原始石弓": {
    "ITEM_MODIFYATTACK": 187,
    "ITEM_MODIFYHITRATE": 17
  },
  "重弦弓": {
    "ITEM_MODIFYATTACK": 187
  },
  "月光長弓+": {
    "ITEM_MODIFYATTACK": 160,
    "ITEM_MODIFYHITRATE": 7
  },
  "平行弓": {
    "ITEM_MODIFYATTACK": 209
  },
  "靈魂之弓": {},
  "摘星之弓": {
    "ITEM_MODIFYATTACK": 231
  },
  "魔彈": {
    "ITEM_MODIFYHITRATE": 7
  },
  "調和之弓": {
    "ITEM_MODIFYATTACK": 230,
    "ITEM_MODIFYCRITICAL": 8,
    "ITEM_MODIFYAVOID": 12
  },
  "月之弓": {
    "ITEM_MODIFYATTACK": 250,
    "ITEM_MODIFYHITRATE": 10
  },
  "短杖": {
    "ITEM_MODIFYMAGIC": 5,
    "ITEM_ADM": 14
  },
  "權杖": {
    "ITEM_MODIFYATTACK": 10,
    "ITEM_ADM": 12
  },
  "大地之杖": {
    "ITEM_MODIFYMAGIC": 10,
    "ITEM_ADM": 48
  },
  "激流權杖": {
    "ITEM_MODIFYATTACK": 20,
    "ITEM_ADM": 45
  },
  "魔之手杖": {
    "ITEM_MODIFYMAGIC": 15,
    "ITEM_ADM": 82
  },
  "魔之權杖": {
    "ITEM_MODIFYATTACK": 30,
    "ITEM_ADM": 77
  },
  "賢者手杖": {
    "ITEM_MODIFYMAGIC": 20,
    "ITEM_ADM": 116
  },
  "賢者權杖": {
    "ITEM_MODIFYATTACK": 40,
    "ITEM_ADM": 110
  },
  "琥珀杖": {
    "ITEM_MODIFYMAGIC": 25,
    "ITEM_ADM": 150
  },
  "琥珀權杖": {
    "ITEM_MODIFYATTACK": 50,
    "ITEM_ADM": 142
  },
  "魔晶之杖": {
    "ITEM_MODIFYATTACK": 53,
    "ITEM_MODIFYRECOVERY": 6,
    "ITEM_ADM": 142
  },
  "元素之杖": {
    "ITEM_MODIFYMAGIC": 30,
    "ITEM_ADM": 184
  },
  "神聖之杖": {
    "ITEM_MODIFYATTACK": 60,
    "ITEM_ADM": 175
  },
  "怒音之杖": {
    "ITEM_MODIFYMAGIC": 35,
    "ITEM_ADM": 218
  },
  "隱者之杖": {
    "ITEM_MODIFYATTACK": 70,
    "ITEM_ADM": 207
  },
  "光明短杖": {
    "ITEM_MODIFYMAGIC": 40,
    "ITEM_ADM": 252
  },
  "惡魔之杖": {
    "ITEM_MODIFYATTACK": 80,
    "ITEM_ADM": 240
  },
  "落雷權杖+": {
    "ITEM_MODIFYATTACK": 70,
    "ITEM_MODIFYMAGIC": 35,
    "ITEM_ADM": 208
  },
  "太陽短杖": {
    "ITEM_MODIFYMAGIC": 45,
    "ITEM_ADM": 286
  },
  "天使之杖": {
    "ITEM_MODIFYATTACK": 90,
    "ITEM_ADM": 272
  },
  "聖者之杖": {
    "ITEM_MODIFYMAGIC": 50,
    "ITEM_ADM": 320
  },
  "星屑短杖": {
    "ITEM_MODIFYATTACK": 100,
    "ITEM_ADM": 305
  },
  "王者之手": {
    "ITEM_MODIFYMAGIC": 60,
    "ITEM_ADM": 354,
    "ITEM_MODIFYAVOID": 12
  },
  "星錘杖": {
    "ITEM_MODIFYATTACK": 180,
    "ITEM_ADM": 252,
    "ITEM_MODIFYHITRATE": 12
  },
  "小刀": {
    "ITEM_MODIFYATTACK": 18,
    "ITEM_MODIFYCRITICAL": 5
  },
  "銳刃小刀": {
    "ITEM_MODIFYATTACK": 27,
    "ITEM_MODIFYCRITICAL": 5
  },
  "圓盤小刀": {
    "ITEM_MODIFYATTACK": 36,
    "ITEM_MODIFYCRITICAL": 5
  },
  "細刃擲刀": {
    "ITEM_MODIFYATTACK": 45,
    "ITEM_MODIFYCRITICAL": 5
  },
  "滑翔小刀": {
    "ITEM_MODIFYATTACK": 54,
    "ITEM_MODIFYCRITICAL": 5
  },
  "細直刃小刀": {
    "ITEM_MODIFYATTACK": 63,
    "ITEM_MODIFYCRITICAL": 5
  },
  "耳柄小刀": {
    "ITEM_MODIFYATTACK": 72,
    "ITEM_MODIFYCRITICAL": 5
  },
  "騎士小刀": {
    "ITEM_MODIFYATTACK": 81,
    "ITEM_MODIFYCRITICAL": 5
  },
  "球鍔小刀": {
    "ITEM_MODIFYATTACK": 90,
    "ITEM_MODIFYCRITICAL": 5
  },
  "雙刃小刀": {
    "ITEM_MODIFYATTACK": 99,
    "ITEM_MODIFYCRITICAL": 5
  },
  "忍者飛鏢": {
    "ITEM_MODIFYATTACK": 110,
    "ITEM_MODIFYAGILITY": 6
  },
  "闊刃小刀": {
    "ITEM_MODIFYATTACK": 108,
    "ITEM_MODIFYCRITICAL": 5
  },
  "觸角小刀": {
    "ITEM_MODIFYATTACK": 117,
    "ITEM_MODIFYCRITICAL": 5
  },
  "漢拉提小刀": {
    "ITEM_MODIFYATTACK": 126,
    "ITEM_MODIFYCRITICAL": 5,
    "ITEM_MODIFYHITRATE": 17
  },
  "凶殺刀": {
    "ITEM_MODIFYATTACK": 135,
    "ITEM_MODIFYCRITICAL": 5
  },
  "切肉小刀": {
    "ITEM_MODIFYCRITICAL": 20,
    "ITEM_MODIFYHITRATE": 17,
    "ITEM_MODIFYAVOID": 17
  },
  "古傳小刀": {
    "ITEM_MODIFYATTACK": 153,
    "ITEM_MODIFYCRITICAL": 5
  },
  "疾速短刀+": {
    "ITEM_MODIFYATTACK": 140,
    "ITEM_MODIFYCRITICAL": 7,
    "ITEM_MODIFYHITRATE": 5
  },
  "華麗小刀": {
    "ITEM_MODIFYATTACK": 171,
    "ITEM_MODIFYCRITICAL": 5
  },
  "手里劍": {
    "ITEM_MODIFYATTACK": 151,
    "ITEM_MODIFYCRITICAL": 8,
    "ITEM_MODIFYHITRATE": 5
  },
  "勾爪擲刀": {
    "ITEM_MODIFYATTACK": 189,
    "ITEM_MODIFYCRITICAL": 5
  },
  "幻之匕首": {
    "ITEM_MODIFYATTACK": 210
  },
  "破滅刀": {
    "ITEM_MODIFYATTACK": 244,
    "ITEM_MODIFYCRITICAL": 4,
    "ITEM_MODIFYHITRATE": 14,
    "ITEM_MODIFYAVOID": 7
  },
  "凶殘刀": {
    "ITEM_MODIFYATTACK": 240,
    "ITEM_MODIFYCRITICAL": 16,
    "ITEM_MODIFYHITRATE": 4
  },
  "木制大型回力鏢": {
    "ITEM_MODIFYATTACK": 23
  },
  "青銅回力鏢": {
    "ITEM_MODIFYATTACK": 35
  },
  "追跡者": {
    "ITEM_MODIFYATTACK": 46
  },
  "彩光回力鏢": {
    "ITEM_MODIFYATTACK": 58
  },
  "暗殺回力鏢": {
    "ITEM_MODIFYATTACK": 69
  },
  "殺敵回力鏢": {
    "ITEM_MODIFYATTACK": 81
  },
  "獅子回力鏢": {
    "ITEM_MODIFYATTACK": 92
  },
  "銳角回力鏢": {
    "ITEM_MODIFYATTACK": 104
  },
  "翼鹿回力鏢": {
    "ITEM_MODIFYATTACK": 115
  },
  "阿修塔羅回力鏢": {
    "ITEM_MODIFYATTACK": 127
  },
  "北斗之鎌刀": {
    "ITEM_MODIFYATTACK": 135,
    "ITEM_MODIFYCRITICAL": 5
  },
  "蛇獅回力鏢": {
    "ITEM_MODIFYATTACK": 138
  },
  "鶇回力鏢": {
    "ITEM_MODIFYATTACK": 150
  },
  "雄翼牛回力鏢": {
    "ITEM_MODIFYATTACK": 173
  },
  "閃光回力鏢": {
    "ITEM_MODIFYATTACK": 140,
    "ITEM_MODIFYCRITICAL": 17
  },
  "凶豹回力鏢": {
    "ITEM_MODIFYATTACK": 196
  },
  "赤獅回力鏢": {
    "ITEM_MODIFYATTACK": 160
  },
  "雄翼牛回力鏢+": {
    "ITEM_MODIFYATTACK": 155,
    "ITEM_MODIFYAGILITY": 20,
    "ITEM_MODIFYAVOID": 5
  },
  "天使之翼": {
    "ITEM_MODIFYATTACK": 219
  },
  "普利辛回力鏢": {
    "ITEM_MODIFYATTACK": 230
  },
  "治愈回力鏢": {
    "ITEM_MODIFYATTACK": 242
  },
  "天秤回力鏢": {
    "ITEM_MODIFYATTACK": 242,
    "ITEM_MODIFYHITRATE": 7,
    "ITEM_MODIFYAVOID": 3
  },
  "基盤飛鏢": {
    "ITEM_MODIFYFORCEPOINT": 200,
    "ITEM_MODIFYATTACK": 220
  },
  "節制飛鏢": {
    "ITEM_MODIFYATTACK": 250,
    "ITEM_MODIFYHITRATE": 8,
    "ITEM_MODIFYAVOID": 12
  },
  "硬皮頭盔": {
    "ITEM_MODIFYDEFENCE": 11,
    "ITEM_RSS": 7
  },
  "銅制頭盔": {
    "ITEM_MODIFYDEFENCE": 17,
    "ITEM_RSS": 5
  },
  "鐵板布盔": {
    "ITEM_MODIFYDEFENCE": 22,
    "ITEM_RSS": 14
  },
  "銅鐵皮盔": {
    "ITEM_MODIFYDEFENCE": 28,
    "ITEM_RSS": 10
  },
  "金屬護額": {
    "ITEM_MODIFYDEFENCE": 33,
    "ITEM_RSS": 21
  },
  "鐵制頭盔": {
    "ITEM_MODIFYDEFENCE": 39,
    "ITEM_RSS": 15
  },
  "霸葛頭盔": {
    "ITEM_MODIFYDEFENCE": 44,
    "ITEM_RSS": 28
  },
  "角飾頭盔": {
    "ITEM_MODIFYDEFENCE": 50,
    "ITEM_RSS": 20
  },
  "開放式頭盔": {
    "ITEM_MODIFYDEFENCE": 55,
    "ITEM_RSS": 35
  },
  "葛理克頭盔": {
    "ITEM_MODIFYDEFENCE": 61,
    "ITEM_RSS": 25
  },
  "聖騎士之盔": {
    "ITEM_MODIFYDEFENCE": 52,
    "ITEM_RSS": 40
  },
  "巴比克頭盔": {
    "ITEM_MODIFYDEFENCE": 66,
    "ITEM_RSS": 42
  },
  "利刃頭盔": {
    "ITEM_MODIFYDEFENCE": 72,
    "ITEM_RSS": 30
  },
  "騎士頭盔": {
    "ITEM_MODIFYDEFENCE": 60,
    "ITEM_RSS": 42
  },
  "鋼製頭盔": {
    "ITEM_MODIFYDEFENCE": 83,
    "ITEM_RSS": 38
  },
  "博流蓋爾頭盔": {
    "ITEM_MODIFYAVOID": 27
  },
  "鉚釘頭盔": {
    "ITEM_MODIFYDEFENCE": 94,
    "ITEM_RSS": 48
  },
  "鋼製頭盔+": {
    "ITEM_MODIFYDEFENCE": 85,
    "ITEM_RSS": 32,
    "ITEM_MODIFYHITRATE": 1,
    "ITEM_MODIFYAVOID": 7
  },
  "羽毛頭盔": {
    "ITEM_MODIFYDEFENCE": 105,
    "ITEM_RSS": 63
  },
  "龍盔": {
    "ITEM_RSS": 36,
    "ITEM_MODIFYHITRATE": 5
  },
  "白金頭盔": {
    "ITEM_MODIFYDEFENCE": 116,
    "ITEM_RSS": 70
  },
  "聖龍頭盔": {
    "ITEM_RSS": 60
  },
  "正義頭盔": {
    "ITEM_MODIFYDEFENCE": 103,
    "ITEM_RSS": 87,
    "ITEM_MODIFYCRITICAL": 8
  },
  "靈力頭盔": {
    "ITEM_MODIFYDEFENCE": 120,
    "ITEM_RSS": 77,
    "ITEM_MODIFYHITRATE": 6,
    "ITEM_MODIFYCOUNTER": 10
  },
  "麻布帽": {
    "ITEM_MODIFYDEFENCE": 7,
    "ITEM_MODIFYHITRATE": 7
  },
  "硬帽": {
    "ITEM_MODIFYDEFENCE": 11,
    "ITEM_MODIFYHITRATE": 7
  },
  "輕帽": {
    "ITEM_MODIFYDEFENCE": 14
  },
  "皮帽": {
    "ITEM_MODIFYDEFENCE": 18
  },
  "硬皮帽": {
    "ITEM_MODIFYDEFENCE": 21
  },
  "可愛的帽子": {
    "ITEM_MODIFYDEFENCE": 25
  },
  "時髦帽子": {
    "ITEM_MODIFYDEFENCE": 28
  },
  "鴨舌帽": {
    "ITEM_MODIFYDEFENCE": 32
  },
  "藍徽章之帽": {
    "ITEM_MODIFYDEFENCE": 35
  },
  "高級帽子": {
    "ITEM_MODIFYDEFENCE": 39
  },
  "劍客帽": {
    "ITEM_MODIFYHP": 75,
    "ITEM_MODIFYDEFENCE": 14,
    "ITEM_MODIFYHITRATE": 7,
    "ITEM_MODIFYAVOID": 5
  },
  "裝飾着花的帽子": {
    "ITEM_MODIFYDEFENCE": 42,
    "ITEM_MODIFYHITRATE": 7
  },
  "青銅帽子": {
    "ITEM_MODIFYDEFENCE": 46,
    "ITEM_MODIFYHITRATE": 7
  },
  "淑女帽": {},
  "可愛的扁帽子": {
    "ITEM_MODIFYDEFENCE": 53,
    "ITEM_MODIFYHITRATE": 7
  },
  "軍帽": {
    "ITEM_MODIFYDEFENCE": 56,
    "ITEM_MODIFYHITRATE": 7
  },
  "時髦避暑帽": {
    "ITEM_MODIFYDEFENCE": 46,
    "ITEM_MODIFYHITRATE": 7
  },
  "可愛的扁帽子+": {
    "ITEM_MODIFYDEFENCE": 45,
    "ITEM_MODIFYHITRATE": 7,
    "ITEM_MODIFYAVOID": 5
  },
  "羽毛帽": {
    "ITEM_MODIFYDEFENCE": 67,
    "ITEM_MODIFYHITRATE": 7
  },
  "魔術師之帽": {
    "ITEM_MODIFYHITRATE": 17
  },
  "黃昏之帽": {
    "ITEM_MODIFYDEFENCE": 74,
    "ITEM_MODIFYHITRATE": 7
  },
  "妖精之帽": {
    "ITEM_MODIFYHITRATE": 7,
    "ITEM_MODIFYAVOID": 4
  },
  "貝斯神帽": {
    "ITEM_MODIFYDEFENCE": 50,
    "ITEM_MODIFYAVOID": 12
  },
  "神官帽": {
    "ITEM_MODIFYDEFENCE": 90,
    "ITEM_MODIFYHITRATE": 12
  },
  "軟皮甲": {
    "ITEM_MODIFYDEFENCE": 21,
    "ITEM_RSS": 8
  },
  "護心甲": {
    "ITEM_MODIFYDEFENCE": 32,
    "ITEM_RSS": 6
  },
  "青銅鎧甲": {
    "ITEM_MODIFYDEFENCE": 42,
    "ITEM_RSS": 16
  },
  "輕型鎧甲": {
    "ITEM_MODIFYDEFENCE": 53,
    "ITEM_RSS": 12
  },
  "輕型鎖鏈甲": {
    "ITEM_MODIFYDEFENCE": 63,
    "ITEM_RSS": 24
  },
  "環甲": {
    "ITEM_MODIFYDEFENCE": 74,
    "ITEM_RSS": 18
  },
  "鋼鐵鎧甲": {
    "ITEM_MODIFYDEFENCE": 84,
    "ITEM_RSS": 32
  },
  "金屬皮甲": {
    "ITEM_MODIFYDEFENCE": 95,
    "ITEM_RSS": 24
  },
  "長型金屬鎧甲": {
    "ITEM_MODIFYDEFENCE": 105,
    "ITEM_RSS": 40
  },
  "索狀鎧甲": {
    "ITEM_MODIFYDEFENCE": 116,
    "ITEM_RSS": 30
  },
  "劍齒鎧甲": {
    "ITEM_MODIFYDEFENCE": 110,
    "ITEM_RSS": 28
  },
  "重鐵板甲": {
    "ITEM_MODIFYDEFENCE": 126,
    "ITEM_RSS": 48
  },
  "鐵板半身甲": {
    "ITEM_MODIFYDEFENCE": 137,
    "ITEM_RSS": 36
  },
  "實戰鎧甲": {
    "ITEM_MODIFYDEFENCE": 147,
    "ITEM_RSS": 56
  },
  "黃金鎧甲": {},
  "重金屬鎧甲": {
    "ITEM_MODIFYDEFENCE": 179,
    "ITEM_RSS": 64
  },
  "野獸之鎧": {
    "ITEM_MODIFYDEFENCE": 140,
    "ITEM_RSS": 24
  },
  "實戰鎧甲+": {
    "ITEM_MODIFYDEFENCE": 150
  },
  "帝王之鎧": {
    "ITEM_MODIFYDEFENCE": 200,
    "ITEM_RSS": 36
  },
  "亡靈鎧甲": {
    "ITEM_MODIFYAVOID": 12
  },
  "漆黑之鎧": {
    "ITEM_MODIFYDEFENCE": 221,
    "ITEM_RSS": 80
  },
  "騎士鎧甲": {
    "ITEM_RSS": 60
  },
  "紅繩威鎧": {
    "ITEM_MODIFYDEFENCE": 225,
    "ITEM_RSS": 60,
    "ITEM_MODIFYHITRATE": 10
  },
  "守護鎧甲": {
    "ITEM_MODIFYHP": 100,
    "ITEM_MODIFYDEFENCE": 255,
    "ITEM_RSS": 100
  },
  "旅人之服": {
    "ITEM_MODIFYDEFENCE": 14,
    "ITEM_MODIFYAVOID": 7
  },
  "保護衣": {
    "ITEM_MODIFYDEFENCE": 21,
    "ITEM_MODIFYAVOID": 7
  },
  "羽毛裝": {
    "ITEM_MODIFYDEFENCE": 28,
    "ITEM_MODIFYAVOID": 7
  },
  "皮裝": {
    "ITEM_MODIFYDEFENCE": 35,
    "ITEM_MODIFYAVOID": 7
  },
  "硬皮服": {
    "ITEM_MODIFYDEFENCE": 42,
    "ITEM_MODIFYAVOID": 7
  },
  "鎖鏈裝": {
    "ITEM_MODIFYDEFENCE": 49,
    "ITEM_MODIFYAVOID": 7
  },
  "布甲": {
    "ITEM_MODIFYDEFENCE": 56,
    "ITEM_MODIFYAVOID": 7
  },
  "櫬甲": {
    "ITEM_MODIFYDEFENCE": 63,
    "ITEM_MODIFYAVOID": 7
  },
  "環服": {
    "ITEM_MODIFYDEFENCE": 70,
    "ITEM_MODIFYAVOID": 7
  },
  "士兵護衣": {
    "ITEM_MODIFYDEFENCE": 77,
    "ITEM_MODIFYAVOID": 7
  },
  "功夫裝": {
    "ITEM_MODIFYDEFENCE": 48,
    "ITEM_RSS": 18
  },
  "長索錐衣": {
    "ITEM_MODIFYDEFENCE": 84,
    "ITEM_MODIFYAVOID": 7
  },
  "索錐上衣": {
    "ITEM_MODIFYDEFENCE": 91,
    "ITEM_MODIFYAVOID": 7
  },
  "骨衣": {
    "ITEM_MODIFYDEFENCE": 105,
    "ITEM_MODIFYAVOID": 7
  },
  "超級衣服": {
    "ITEM_MODIFYDEFENCE": 98,
    "ITEM_MODIFYAVOID": 7
  },
  "疾風之衣": {
    "ITEM_MODIFYDEFENCE": 112,
    "ITEM_MODIFYHITRATE": 4,
    "ITEM_MODIFYAVOID": 7
  },
  "步兵戰衣": {
    "ITEM_MODIFYDEFENCE": 119,
    "ITEM_MODIFYAVOID": 7
  },
  "獸骨之衣+": {
    "ITEM_MODIFYDEFENCE": 115,
    "ITEM_MODIFYAGILITY": 20,
    "ITEM_MODIFYAVOID": 7
  },
  "勇者之衣": {
    "ITEM_MODIFYDEFENCE": 133,
    "ITEM_MODIFYAVOID": 7
  },
  "女神之衣": {
    "ITEM_MODIFYHITRATE": 4,
    "ITEM_MODIFYAVOID": 17
  },
  "不死鳥之服": {
    "ITEM_MODIFYDEFENCE": 147,
    "ITEM_MODIFYAVOID": 7
  },
  "靈魂之服": {
    "ITEM_MODIFYHITRATE": 4,
    "ITEM_MODIFYAVOID": 7
  },
  "海洋之服": {
    "ITEM_MODIFYDEFENCE": 190,
    "ITEM_MODIFYHITRATE": 7
  },
  "幻想之服": {
    "ITEM_MODIFYDEFENCE": 110,
    "ITEM_MODIFYCRITICAL": 7
  },
  "羽毛袍": {
    "ITEM_MODIFYFORCEPOINT": 50,
    "ITEM_MODIFYDEFENCE": 8
  },
  "輕皮袍": {
    "ITEM_MODIFYFORCEPOINT": 75,
    "ITEM_MODIFYDEFENCE": 12
  },
  "網袍": {
    "ITEM_MODIFYFORCEPOINT": 100,
    "ITEM_MODIFYDEFENCE": 16
  },
  "風袍": {
    "ITEM_MODIFYFORCEPOINT": 125,
    "ITEM_MODIFYDEFENCE": 20
  },
  "硬皮袍": {
    "ITEM_MODIFYFORCEPOINT": 150,
    "ITEM_MODIFYDEFENCE": 24
  },
  "環袍": {
    "ITEM_MODIFYFORCEPOINT": 175,
    "ITEM_MODIFYDEFENCE": 28
  },
  "烏鴉之袍": {
    "ITEM_MODIFYFORCEPOINT": 200,
    "ITEM_MODIFYDEFENCE": 32
  },
  "月亮之袍": {
    "ITEM_MODIFYFORCEPOINT": 225,
    "ITEM_MODIFYDEFENCE": 36
  },
  "狐皮披風": {
    "ITEM_MODIFYFORCEPOINT": 60,
    "ITEM_MODIFYDEFENCE": 24,
    "ITEM_MODIFYAGILITY": 12
  },
  "東方法衣": {
    "ITEM_MODIFYFORCEPOINT": 250,
    "ITEM_MODIFYDEFENCE": 40
  },
  "聖堂之袍": {
    "ITEM_MODIFYFORCEPOINT": 275,
    "ITEM_MODIFYDEFENCE": 44
  },
  "治愈之袍": {
    "ITEM_MODIFYFORCEPOINT": 170,
    "ITEM_MODIFYDEFENCE": 75
  },
  "聖者之袍": {
    "ITEM_MODIFYFORCEPOINT": 300,
    "ITEM_MODIFYDEFENCE": 48
  },
  "戰斗長袍": {
    "ITEM_MODIFYFORCEPOINT": 325,
    "ITEM_MODIFYDEFENCE": 52
  },
  "冠軍之袍": {},
  "時之袍": {
    "ITEM_MODIFYFORCEPOINT": 375,
    "ITEM_MODIFYDEFENCE": 60
  },
  "死神之袍": {
    "ITEM_MODIFYFORCEPOINT": 400,
    "ITEM_MODIFYDEFENCE": 64
  },
  "勇者之袍": {
    "ITEM_MODIFYFORCEPOINT": 425,
    "ITEM_MODIFYDEFENCE": 68
  },
  "潔淨之袍+": {
    "ITEM_MODIFYFORCEPOINT": 400,
    "ITEM_MODIFYDEFENCE": 61,
    "ITEM_MODIFYRECOVERY": 5
  },
  "黑暗之袍": {
    "ITEM_MODIFYFORCEPOINT": 475,
    "ITEM_MODIFYDEFENCE": 76
  },
  "聖袍": {},
  "靈魂之袍": {
    "ITEM_MODIFYFORCEPOINT": 525,
    "ITEM_MODIFYDEFENCE": 84
  },
  "奇蹟之袍": {},
  "共嗚之袍": {
    "ITEM_MODIFYFORCEPOINT": 550,
    "ITEM_MODIFYDEFENCE": 35,
    "ITEM_MODIFYAVOID": 12
  },
  "和平之袍": {
    "ITEM_MODIFYFORCEPOINT": 200,
    "ITEM_MODIFYDEFENCE": 121,
    "ITEM_MODIFYCRITICAL": 12
  },
  "軟皮靴": {
    "ITEM_MODIFYDEFENCE": 10,
    "ITEM_RSS": 5
  },
  "皮靴": {
    "ITEM_MODIFYDEFENCE": 15,
    "ITEM_RSS": 3
  },
  "硬皮靴": {
    "ITEM_MODIFYDEFENCE": 19,
    "ITEM_RSS": 10
  },
  "長靴": {
    "ITEM_MODIFYDEFENCE": 24,
    "ITEM_RSS": 6
  },
  "厚底靴": {
    "ITEM_MODIFYDEFENCE": 29,
    "ITEM_RSS": 15
  },
  "編織的靴子": {
    "ITEM_MODIFYDEFENCE": 34,
    "ITEM_RSS": 9
  },
  "鎖鏈長靴": {
    "ITEM_MODIFYDEFENCE": 38,
    "ITEM_RSS": 20
  },
  "鎖鏈靴": {
    "ITEM_MODIFYDEFENCE": 43,
    "ITEM_RSS": 12
  },
  "蜥蜴靴": {
    "ITEM_MODIFYDEFENCE": 48,
    "ITEM_RSS": 25
  },
  "蜥蜴長靴": {
    "ITEM_MODIFYDEFENCE": 53,
    "ITEM_RSS": 15
  },
  "防護靴": {
    "ITEM_MODIFYDEFENCE": 20,
    "ITEM_RSS": 10
  },
  "鋼靴": {
    "ITEM_MODIFYDEFENCE": 57,
    "ITEM_RSS": 30
  },
  "鋼制長靴": {
    "ITEM_MODIFYDEFENCE": 62,
    "ITEM_RSS": 18
  },
  "水晶靴": {
    "ITEM_MODIFYDEFENCE": 72,
    "ITEM_RSS": 35
  },
  "銀靴": {
    "ITEM_MODIFYDEFENCE": 67
  },
  "流水之靴": {
    "ITEM_MODIFYDEFENCE": 81,
    "ITEM_RSS": 40
  },
  "芙蕾雅之靴": {
    "ITEM_MODIFYCRITICAL": 6,
    "ITEM_MODIFYCOUNTER": 6
  },
  "標準長靴+": {
    "ITEM_MODIFYDEFENCE": 75,
    "ITEM_RSS": 24,
    "ITEM_MODIFYAVOID": 5
  },
  "鑽石靴": {
    "ITEM_MODIFYDEFENCE": 91,
    "ITEM_RSS": 45
  },
  "鑽石長靴": {
    "ITEM_MODIFYCRITICAL": 5,
    "ITEM_MODIFYHITRATE": 4,
    "ITEM_MODIFYCOUNTER": 5
  },
  "秘密之靴": {
    "ITEM_MODIFYDEFENCE": 100,
    "ITEM_RSS": 50
  },
  "龍之靴": {
    "ITEM_MODIFYHITRATE": 5,
    "ITEM_MODIFYAVOID": 5
  },
  "幸運靴": {
    "ITEM_MODIFYDEFENCE": 90,
    "ITEM_RSS": 25,
    "ITEM_MODIFYAVOID": 12
  },
  "試力鞋": {
    "ITEM_MODIFYDEFENCE": 120,
    "ITEM_RSS": 60,
    "ITEM_MODIFYCOUNTER": 8
  },
  "運動鞋": {
    "ITEM_MODIFYDEFENCE": 3,
    "ITEM_MODIFYAGILITY": 4
  },
  "馬車鞋": {
    "ITEM_MODIFYDEFENCE": 5,
    "ITEM_MODIFYAGILITY": 6
  },
  "皮鞋": {
    "ITEM_MODIFYDEFENCE": 6,
    "ITEM_MODIFYAGILITY": 8
  },
  "安全鞋": {
    "ITEM_MODIFYDEFENCE": 4,
    "ITEM_MODIFYAGILITY": 10
  },
  "光之鞋": {
    "ITEM_MODIFYDEFENCE": 9,
    "ITEM_MODIFYAGILITY": 12
  },
  "戰鞋": {
    "ITEM_MODIFYDEFENCE": 11,
    "ITEM_MODIFYAGILITY": 14
  },
  "薄板鞋": {
    "ITEM_MODIFYDEFENCE": 12,
    "ITEM_MODIFYAGILITY": 16
  },
  "鎖鏈鞋": {
    "ITEM_MODIFYDEFENCE": 14,
    "ITEM_MODIFYAGILITY": 18
  },
  "蜥蜴鞋": {
    "ITEM_MODIFYDEFENCE": 15,
    "ITEM_MODIFYAGILITY": 20
  },
  "維京鞋": {
    "ITEM_MODIFYDEFENCE": 17,
    "ITEM_MODIFYAGILITY": 22
  },
  "特製舞鞋": {
    "ITEM_MODIFYDEFENCE": 15,
    "ITEM_MODIFYAGILITY": 21
  },
  "戰斗鞋": {
    "ITEM_MODIFYDEFENCE": 18,
    "ITEM_MODIFYAGILITY": 24
  },
  "騎士鞋": {
    "ITEM_MODIFYDEFENCE": 20,
    "ITEM_MODIFYAGILITY": 26
  },
  "妖精鞋": {
    "ITEM_MODIFYDEFENCE": 23,
    "ITEM_MODIFYAGILITY": 30
  },
  "紫水晶鞋": {
    "ITEM_MODIFYDEFENCE": 54
  },
  "白金鞋": {
    "ITEM_MODIFYDEFENCE": 26,
    "ITEM_MODIFYAGILITY": 32
  },
  "精緻高根鞋": {
    "ITEM_MODIFYDEFENCE": 26
  },
  "妖精鞋+": {
    "ITEM_MODIFYDEFENCE": 24,
    "ITEM_MODIFYAGILITY": 40
  },
  "神秘之鞋": {
    "ITEM_MODIFYDEFENCE": 29,
    "ITEM_MODIFYAGILITY": 38
  },
  "力量之鞋": {},
  "黃金鞋": {
    "ITEM_MODIFYDEFENCE": 32,
    "ITEM_MODIFYAGILITY": 42
  },
  "龍之鞋": {
    "ITEM_MODIFYDEFENCE": 42,
    "ITEM_MODIFYAGILITY": 37,
    "ITEM_MODIFYAVOID": 5
  },
  "守護之鞋": {
    "ITEM_MODIFYDEFENCE": 15,
    "ITEM_MODIFYAGILITY": 65,
    "ITEM_MODIFYAVOID": 17
  },
  "大木屐": {
    "ITEM_MODIFYDEFENCE": 68,
    "ITEM_MODIFYAGILITY": 13,
    "ITEM_MODIFYCRITICAL": 8
  },
  "小圓盾": {
    "ITEM_MODIFYDEFENCE": 11,
    "ITEM_RSS": 12
  },
  "小型盾": {
    "ITEM_MODIFYDEFENCE": 17,
    "ITEM_RSS": 10
  },
  "板盾": {
    "ITEM_MODIFYDEFENCE": 22,
    "ITEM_RSS": 24
  },
  "鳶盾": {
    "ITEM_MODIFYDEFENCE": 28,
    "ITEM_RSS": 20
  },
  "漩渦重盾": {
    "ITEM_MODIFYDEFENCE": 33,
    "ITEM_RSS": 36
  },
  "哥特盾": {
    "ITEM_MODIFYDEFENCE": 39,
    "ITEM_RSS": 30
  },
  "士兵盾": {
    "ITEM_MODIFYDEFENCE": 44,
    "ITEM_RSS": 48
  },
  "重盾": {
    "ITEM_MODIFYDEFENCE": 50,
    "ITEM_RSS": 40
  },
  "蜥蜴盾": {
    "ITEM_MODIFYDEFENCE": 55,
    "ITEM_RSS": 60
  },
  "反光之盾": {
    "ITEM_MODIFYDEFENCE": 61,
    "ITEM_RSS": 50
  },
  "聖者之盾": {
    "ITEM_MODIFYFORCEPOINT": 120,
    "ITEM_MODIFYDEFENCE": 29,
    "ITEM_RSS": 55
  },
  "風之盾": {
    "ITEM_MODIFYDEFENCE": 66,
    "ITEM_RSS": 72
  },
  "獅子盾": {
    "ITEM_MODIFYDEFENCE": 72,
    "ITEM_RSS": 60
  },
  "防守之盾": {
    "ITEM_MODIFYDEFENCE": 77,
    "ITEM_RSS": 84
  },
  "黃金之盾": {
    "ITEM_MODIFYDEFENCE": 103,
    "ITEM_RSS": 70
  },
  "鏡之盾": {
    "ITEM_MODIFYDEFENCE": 88,
    "ITEM_RSS": 96
  },
  "力量之盾": {
    "ITEM_RSS": 40,
    "ITEM_MODIFYAVOID": 10
  },
  "防御之盾+": {
    "ITEM_MODIFYATTACK": 20,
    "ITEM_MODIFYDEFENCE": 79,
    "ITEM_RSS": 80
  },
  "漆黑之盾": {
    "ITEM_MODIFYDEFENCE": 105,
    "ITEM_RSS": 108
  },
  "火龍之盾": {
    "ITEM_RSS": 45,
    "ITEM_MODIFYHITRATE": 4,
    "ITEM_MODIFYAVOID": 12
  },
  "黑暗之盾": {
    "ITEM_MODIFYDEFENCE": 116
  },
  "勇者之盾": {},
  "突猛盾": {
    "ITEM_MODIFYDEFENCE": 136,
    "ITEM_RSS": 100,
    "ITEM_MODIFYHITRATE": 10
  },
  "重型防御盾": {
    "ITEM_MODIFYDEFENCE": 106,
    "ITEM_RSS": 145,
    "ITEM_MODIFYCRITICAL": 8
  },
  "弗旦頭盔": {
    "ITEM_MODIFYDEFENCE": 92,
    "ITEM_RSS": 46
  },
  "弗旦帽": {
    "ITEM_MODIFYDEFENCE": 45
  },
  "弗旦鎧": {
    "ITEM_MODIFYDEFENCE": 172,
    "ITEM_MODIFYAGILITY": 5,
    "ITEM_RSS": 34
  },
  "弗旦衣": {
    "ITEM_MODIFYDEFENCE": 120
  },
  "弗旦之袍": {
    "ITEM_MODIFYFORCEPOINT": 432,
    "ITEM_MODIFYDEFENCE": 67,
    "ITEM_ADM": 1
  },
  "弗旦靴": {},
  "弗旦鞋": {
    "ITEM_MODIFYDEFENCE": 24,
    "ITEM_MODIFYAGILITY": 10
  },
  "弗旦之盾": {
    "ITEM_RSS": 43
  },
  "弗旦之戒": {
    "ITEM_MODIFYRECOVERY": 20,
    "ITEM_MODIFYMAGIC": 20,
    "ITEM_ADM": 3
  },
  "弗旦頭盔+": {
    "ITEM_MODIFYAGILITY": 30
  },
  "弗旦帽+": {
    "ITEM_MODIFYRECOVERY": 20
  },
  "弗旦鎧+": {
    "ITEM_MODIFYFORCEPOINT": 300
  },
  "弗旦衣+": {},
  "弗旦之袍+": {
    "ITEM_MODIFYATTACK": 180,
    "ITEM_MODIFYDEFENCE": 67
  },
  "弗旦靴+": {},
  "弗旦鞋+": {
    "ITEM_MODIFYAGILITY": 24,
    "ITEM_MODIFYMAGIC": 10
  },
  "弗旦之盾+": {
    "ITEM_MODIFYFORCEPOINT": 65
  },
  "弗旦之戒+": {
    "ITEM_MODIFYATTACK": 38,
    "ITEM_MODIFYRECOVERY": 14,
    "ITEM_RSS": 10
  },
  "水龍之劍": {},
  "水龍之斧": {
    "ITEM_MODIFYCRITICAL": 20
  },
  "水龍之槍": {
    "ITEM_MODIFYCRITICAL": 14,
    "ITEM_MODIFYHITRATE": 8
  },
  "水龍之弓": {
    "ITEM_MODIFYCRITICAL": 4,
    "ITEM_MODIFYHITRATE": 22
  },
  "水龍之杖": {},
  "水龍的小刀": {
    "ITEM_MODIFYHITRATE": 27
  },
  "冰龍": {
    "ITEM_MODIFYCRITICAL": 22
  },
  "水龍之盔": {},
  "水龍之帽": {
    "ITEM_MODIFYHITRATE": 7
  },
  "水龍鎧甲": {},
  "水龍之衣": {
    "ITEM_MODIFYHITRATE": 62
  },
  "水龍法袍": {},
  "水龍之靴": {
    "ITEM_MODIFYCRITICAL": 7,
    "ITEM_MODIFYHITRATE": 7
  },
  "水龍之鞋": {
    "ITEM_MODIFYHITRATE": 4,
    "ITEM_MODIFYAVOID": 4
  },
  "水龍之盾": {
    "ITEM_MODIFYCRITICAL": 7,
    "ITEM_MODIFYCOUNTER": 7
  },
  "水晶鏈墜": {
    "ITEM_MODIFYCRITICAL": 20,
    "ITEM_MODIFYAVOID": 20
  },
  "屈原的戒指": {
    "ITEM_MODIFYATTACK": 30,
    "ITEM_MODIFYDEFENCE": 30,
    "ITEM_MODIFYMAGIC": 30,
    "ITEM_RSS": 30,
    "ITEM_MODIFYCRITICAL": 20,
    "ITEM_MODIFYAVOID": 20
  },
  "狂怒繃帶": {
    "ITEM_MODIFYATTACK": 40,
    "ITEM_MODIFYCRITICAL": 15,
    "ITEM_MODIFYHITRATE": 100
  },
  "「年」的頸圈": {
    "ITEM_MODIFYCRITICAL": 5
  },
  "受詛咒的姜餅人": {
    "ITEM_MODIFYDEFENCE": 20,
    "ITEM_MODIFYAGILITY": 20,
    "ITEM_MODIFYAVOID": 15
  },
  "洗禮的護符": {
    "ITEM_MODIFYHP": 100,
    "ITEM_MODIFYFORCEPOINT": 50,
    "ITEM_MODIFYATTACK": 50,
    "ITEM_MODIFYDEFENCE": 40,
    "ITEM_MODIFYAGILITY": 30,
    "ITEM_MODIFYRECOVERY": 10,
    "ITEM_MODIFYMAGIC": 10,
    "ITEM_MODIFYCRITICAL": 10,
    "ITEM_MODIFYHITRATE": 10,
    "ITEM_MODIFYCOUNTER": 10,
    "ITEM_MODIFYAVOID": 10
  },
  "真·戰符": {
    "ITEM_MODIFYHP": 200,
    "ITEM_MODIFYFORCEPOINT": 200,
    "ITEM_MODIFYCRITICAL": 20,
    "ITEM_MODIFYHITRATE": 20,
    "ITEM_MODIFYCOUNTER": 20,
    "ITEM_MODIFYAVOID": 20
  },
  "英靈之誓": {
    "byItemId": {
      "1007001": {},
      "1007002": {
        "ITEM_MODIFYHP": 20,
        "ITEM_MODIFYFORCEPOINT": 20,
        "ITEM_MODIFYRECOVERY": 20,
        "ITEM_MODIFYMAGIC": 20,
        "ITEM_MODIFYCRITICAL": 20,
        "ITEM_RSS": 20
      },
      "1007003": {
        "ITEM_MODIFYHP": 20,
        "ITEM_MODIFYFORCEPOINT": 20,
        "ITEM_MODIFYRECOVERY": 20,
        "ITEM_MODIFYMAGIC": 20,
        "ITEM_ADM": 20,
        "ITEM_MODIFYCOUNTER": 20
      }
    }
  },
  "血盟之衣": {},
  "禍害之裳": {},
  "無情之裳": {},
  "凜冽之裳": {},
  "炙熱之裳": {},
  "大地之裳": {},
  "海洋之裳": {},
  "火焰之裳": {},
  "雲群之裳": {},
  "結界之裳": {},
  "城堡之裳": {},
  "魔消之裳": {},
  "兵消之裳": {},
  "魔靈之裳": {},
  "戰靈之裳": {},
  "氤氳之裳": {}
};

/** Per-stat [min, max] roll range, from the guide's equipment catalogue. */
export const EQUIPMENT_STAT_RANGES: Record<string, Record<string, [number, number]>> = {
  "英靈之誓": {
    "ITEM_MODIFYAGILITY": [
      4,
      20
    ],
    "ITEM_MODIFYDEFENCE": [
      4,
      20
    ],
    "ITEM_MODIFYMAGIC": [
      4,
      20
    ],
    "ITEM_ADM": [
      4,
      20
    ],
    "ITEM_MODIFYATTACK": [
      4,
      20
    ],
    "ITEM_MODIFYCRITICAL": [
      4,
      20
    ],
    "ITEM_MODIFYCOUNTER": [
      4,
      20
    ],
    "ITEM_MODIFYHP": [
      4,
      20
    ],
    "ITEM_RSS": [
      4,
      20
    ],
    "ITEM_MODIFYRECOVERY": [
      4,
      20
    ],
    "ITEM_MODIFYFORCEPOINT": [
      4,
      20
    ]
  },
  "洗禮的護符": {
    "ITEM_MODIFYRECOVERY": [
      2,
      10
    ],
    "ITEM_MODIFYHP": [
      20,
      100
    ],
    "ITEM_MODIFYAVOID": [
      1,
      10
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      10
    ],
    "ITEM_MODIFYMAGIC": [
      2,
      10
    ],
    "ITEM_MODIFYATTACK": [
      10,
      50
    ],
    "ITEM_MODIFYDEFENCE": [
      8,
      40
    ],
    "ITEM_MODIFYCOUNTER": [
      1,
      10
    ],
    "ITEM_MODIFYAGILITY": [
      6,
      30
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      10
    ]
  },
  "真・戰符": {
    "ITEM_MODIFYCOUNTER": [
      15,
      20
    ],
    "ITEM_MODIFYAVOID": [
      15,
      20
    ],
    "ITEM_MODIFYCRITICAL": [
      15,
      20
    ],
    "ITEM_MODIFYHP": [
      150,
      200
    ],
    "ITEM_MODIFYHITRATE": [
      15,
      20
    ]
  },
  "軟皮甲": {
    "ITEM_RSS": [
      6,
      8
    ],
    "ITEM_MODIFYDEFENCE": [
      11,
      21
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "護心甲": {
    "ITEM_RSS": [
      4,
      6
    ],
    "ITEM_MODIFYDEFENCE": [
      16,
      32
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "青銅鎧甲": {
    "ITEM_RSS": [
      12,
      16
    ],
    "ITEM_MODIFYDEFENCE": [
      23,
      42
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "輕型鎧甲": {
    "ITEM_RSS": [
      8,
      12
    ],
    "ITEM_MODIFYDEFENCE": [
      29,
      53
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "輕型鎖鍊甲": {
    "ITEM_RSS": [
      18,
      24
    ],
    "ITEM_MODIFYDEFENCE": [
      38,
      63
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "環甲": {
    "ITEM_RSS": [
      12,
      18
    ],
    "ITEM_MODIFYDEFENCE": [
      44,
      74
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "金屬皮甲": {
    "ITEM_RSS": [
      16,
      24
    ],
    "ITEM_MODIFYDEFENCE": [
      62,
      95
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "鋼鐵鎧甲": {
    "ITEM_RSS": [
      24,
      32
    ],
    "ITEM_MODIFYDEFENCE": [
      55,
      84
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "長型金屬鎧甲": {
    "ITEM_RSS": [
      30,
      40
    ],
    "ITEM_MODIFYDEFENCE": [
      74,
      105
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "索狀鎧甲": {
    "ITEM_RSS": [
      20,
      30
    ],
    "ITEM_MODIFYDEFENCE": [
      81,
      116
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "劍齒鎧甲": {
    "ITEM_MODIFYDEFENCE": [
      100,
      110
    ],
    "ITEM_RSS": [
      18,
      28
    ]
  },
  "重鐵板甲": {
    "ITEM_RSS": [
      36,
      48
    ],
    "ITEM_MODIFYDEFENCE": [
      95,
      126
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "鐵板半身甲": {
    "ITEM_RSS": [
      24,
      36
    ],
    "ITEM_MODIFYDEFENCE": [
      103,
      137
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "黃金鎧甲": {
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "實戰鎧甲": {
    "ITEM_RSS": [
      42,
      56
    ],
    "ITEM_MODIFYDEFENCE": [
      110,
      147
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "重金屬鎧甲": {
    "ITEM_RSS": [
      48,
      64
    ],
    "ITEM_MODIFYDEFENCE": [
      126,
      179
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "野獸之鎧": {
    "ITEM_MODIFYDEFENCE": [
      130,
      140
    ],
    "ITEM_RSS": [
      16,
      24
    ]
  },
  "實戰鎧甲+": {
    "ITEM_MODIFYAGILITY": [
      -9,
      -5
    ],
    "ITEM_MODIFYDEFENCE": [
      115,
      150
    ],
    "ITEM_MODIFYAVOID": [
      -8,
      -7
    ]
  },
  "亡靈鎧甲": {
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "帝王之鎧": {
    "ITEM_RSS": [
      27,
      36
    ],
    "ITEM_MODIFYDEFENCE": [
      160,
      200
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "漆黑之鎧": {
    "ITEM_RSS": [
      70,
      80
    ],
    "ITEM_MODIFYDEFENCE": [
      188,
      221
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "騎士鎧甲": {
    "ITEM_MODIFYAVOID": [
      -9,
      -5
    ],
    "ITEM_RSS": [
      50,
      60
    ]
  },
  "守護鎧甲": {
    "ITEM_RSS": [
      90,
      100
    ],
    "ITEM_MODIFYHP": [
      75,
      100
    ],
    "ITEM_MODIFYDEFENCE": [
      227,
      255
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "紅繩威鎧": {
    "ITEM_RSS": [
      50,
      60
    ],
    "ITEM_MODIFYHITRATE": [
      6,
      10
    ],
    "ITEM_MODIFYDEFENCE": [
      214,
      222
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "手斧": {
    "ITEM_MODIFYAGILITY": [
      -6,
      -5
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      15,
      29
    ]
  },
  "勇氣之斧": {
    "ITEM_MODIFYAGILITY": [
      -9,
      -7
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      22,
      44
    ]
  },
  "寬手斧": {
    "ITEM_MODIFYAGILITY": [
      -12,
      -10
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      32,
      58
    ]
  },
  "戰鬥手斧": {
    "ITEM_MODIFYAGILITY": [
      -15,
      -12
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      40,
      73
    ]
  },
  "格鬥手斧": {
    "ITEM_MODIFYAGILITY": [
      -18,
      -14
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      52,
      87
    ]
  },
  "鋼斧": {
    "ITEM_MODIFYAGILITY": [
      -21,
      -17
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      61,
      102
    ]
  },
  "長戰斧": {
    "ITEM_MODIFYAGILITY": [
      -24,
      -19
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      75,
      116
    ]
  },
  "雙刃斧": {
    "ITEM_MODIFYAGILITY": [
      -27,
      -22
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      85,
      131
    ]
  },
  "鉤爪斧": {
    "ITEM_MODIFYAGILITY": [
      -30,
      -24
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      102,
      145
    ]
  },
  "闊刃斧": {
    "ITEM_MODIFYAGILITY": [
      -33,
      -26
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      112,
      160
    ]
  },
  "鑽保雷格之斧": {
    "ITEM_MODIFYCOUNTER": [
      1,
      4
    ],
    "ITEM_MODIFYAGILITY": [
      -30,
      -24
    ],
    "ITEM_MODIFYATTACK": [
      100,
      169
    ]
  },
  "大型闊刃斧": {
    "ITEM_MODIFYAGILITY": [
      -39,
      -31
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      142,
      189
    ]
  },
  "彎月大戰斧": {
    "ITEM_MODIFYAGILITY": [
      -29,
      -36
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      131,
      174
    ]
  },
  "大型雙刃斧": {
    "ITEM_MODIFYAGILITY": [
      -45,
      -36
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      164,
      218
    ]
  },
  "超大皇帝斧": {
    "ITEM_MODIFYAGILITY": [
      -42,
      -34
    ],
    "ITEM_MODIFYCRITICAL": [
      34,
      38
    ],
    "ITEM_MODIFYATTACK": [
      120,
      145
    ]
  },
  "大型雙刃斧+": {
    "ITEM_MODIFYDEFENCE": [
      -15,
      -10
    ],
    "ITEM_MODIFYCOUNTER": [
      -1,
      5
    ],
    "ITEM_MODIFYAGILITY": [
      -40,
      -28
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      168,
      225
    ]
  },
  "米諾陶斯戰斧": {
    "ITEM_MODIFYATTACK": [
      200,
      245
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ]
  },
  "新月斧": {
    "ITEM_MODIFYAGILITY": [
      -48,
      -38
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      174,
      232
    ]
  },
  "薄刃鉤爪斧": {
    "ITEM_MODIFYAGILITY": [
      -57,
      -46
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      221,
      276
    ]
  },
  "彎月長柄斧": {
    "ITEM_MODIFYAGILITY": [
      -51,
      -50
    ],
    "ITEM_MODIFYCRITICAL": [
      19,
      23
    ],
    "ITEM_MODIFYATTACK": [
      221,
      276
    ]
  },
  "金屬重斧": {
    "ITEM_MODIFYAGILITY": [
      -63,
      -54
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYATTACK": [
      259,
      305
    ]
  },
  "處刑斧": {
    "ITEM_MODIFYATTACK": [
      305,
      310
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ]
  },
  "重擊斧": {
    "ITEM_MODIFYAGILITY": [
      -82,
      -73
    ],
    "ITEM_MODIFYCRITICAL": [
      34,
      38
    ],
    "ITEM_MODIFYATTACK": [
      340,
      379
    ]
  },
  "高速斧": {
    "ITEM_MODIFYATTACK": [
      287,
      312
    ],
    "ITEM_MODIFYCRITICAL": [
      10,
      14
    ]
  },
  "木製大型回力鏢": {
    "ITEM_MODIFYATTACK": [
      12,
      23
    ]
  },
  "青銅回力鏢": {
    "ITEM_MODIFYATTACK": [
      18,
      35
    ]
  },
  "追跡者": {
    "ITEM_MODIFYATTACK": [
      25,
      46
    ]
  },
  "彩光回力鏢": {
    "ITEM_MODIFYATTACK": [
      32,
      58
    ]
  },
  "殺敵回力鏢": {
    "ITEM_MODIFYATTACK": [
      49,
      81
    ]
  },
  "暗殺回力鏢": {
    "ITEM_MODIFYATTACK": [
      41,
      69
    ]
  },
  "獅子回力鏢": {
    "ITEM_MODIFYATTACK": [
      60,
      92
    ]
  },
  "銳角回力鏢": {
    "ITEM_MODIFYATTACK": [
      68,
      104
    ]
  },
  "北斗之鎌刀": {
    "ITEM_MODIFYATTACK": [
      85,
      135
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "阿修塔羅回力鏢": {
    "ITEM_MODIFYATTACK": [
      89,
      127
    ]
  },
  "翼鹿回力鏢": {
    "ITEM_MODIFYATTACK": [
      81,
      115
    ]
  },
  "蛇獅回力鏢": {
    "ITEM_MODIFYATTACK": [
      104,
      138
    ]
  },
  "鶇回力鏢": {
    "ITEM_MODIFYATTACK": [
      113,
      150
    ]
  },
  "閃光回力鏢": {
    "ITEM_MODIFYATTACK": [
      130,
      140
    ],
    "ITEM_MODIFYCRITICAL": [
      13,
      17
    ]
  },
  "雄翼牛回力鏢": {
    "ITEM_MODIFYATTACK": [
      130,
      173
    ]
  },
  "凶豹回力鏢": {
    "ITEM_MODIFYATTACK": [
      147,
      196
    ]
  },
  "赤獅回力鏢": {
    "ITEM_MODIFYATTACK": [
      130,
      160
    ]
  },
  "熊翼牛回力鏢+": {
    "ITEM_MODIFYAGILITY": [
      10,
      20
    ],
    "ITEM_MODIFYATTACK": [
      130,
      155
    ],
    "ITEM_MODIFYAVOID": [
      -1,
      5
    ]
  },
  "天使之翼": {
    "ITEM_MODIFYATTACK": [
      175,
      219
    ]
  },
  "普利辛回力鏢": {
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ],
    "ITEM_MODIFYATTACK": [
      220,
      230
    ]
  },
  "天秤回力鏢": {
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ],
    "ITEM_MODIFYATTACK": [
      236,
      242
    ],
    "ITEM_MODIFYAVOID": [
      -1,
      3
    ]
  },
  "治癒回力鏢": {
    "ITEM_MODIFYATTACK": [
      216,
      242
    ]
  },
  "基盤飛鏢": {
    "ITEM_MODIFYATTACK": [
      200,
      220
    ]
  },
  "節制飛鏢": {
    "ITEM_MODIFYHITRATE": [
      4,
      8
    ],
    "ITEM_MODIFYATTACK": [
      228,
      250
    ],
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "皮靴": {
    "ITEM_MODIFYDEFENCE": [
      8,
      15
    ],
    "ITEM_RSS": [
      1,
      3
    ]
  },
  "軟皮靴": {
    "ITEM_MODIFYDEFENCE": [
      5,
      10
    ],
    "ITEM_RSS": [
      3,
      5
    ]
  },
  "長靴": {
    "ITEM_MODIFYDEFENCE": [
      13,
      24
    ],
    "ITEM_RSS": [
      2,
      6
    ]
  },
  "硬皮靴": {
    "ITEM_MODIFYDEFENCE": [
      10,
      19
    ],
    "ITEM_RSS": [
      6,
      10
    ]
  },
  "厚底靴": {
    "ITEM_MODIFYDEFENCE": [
      17,
      29
    ],
    "ITEM_RSS": [
      9,
      15
    ]
  },
  "編織的靴子": {
    "ITEM_MODIFYDEFENCE": [
      20,
      34
    ],
    "ITEM_RSS": [
      3,
      9
    ]
  },
  "鎖鍊長靴": {
    "ITEM_MODIFYDEFENCE": [
      25,
      38
    ],
    "ITEM_RSS": [
      12,
      20
    ]
  },
  "鎖鍊靴": {
    "ITEM_MODIFYDEFENCE": [
      28,
      43
    ],
    "ITEM_RSS": [
      4,
      12
    ]
  },
  "防護靴": {
    "ITEM_MODIFYDEFENCE": [
      16,
      20
    ],
    "ITEM_RSS": [
      1,
      10
    ]
  },
  "蜥蝪長靴": {
    "ITEM_MODIFYDEFENCE": [
      37,
      53
    ],
    "ITEM_RSS": [
      5,
      15
    ]
  },
  "蜥蝪靴": {
    "ITEM_MODIFYDEFENCE": [
      34,
      48
    ],
    "ITEM_RSS": [
      15,
      25
    ]
  },
  "鋼靴": {
    "ITEM_MODIFYDEFENCE": [
      43,
      57
    ],
    "ITEM_RSS": [
      18,
      30
    ]
  },
  "鋼製長靴": {
    "ITEM_MODIFYDEFENCE": [
      47,
      62
    ],
    "ITEM_RSS": [
      6,
      18
    ]
  },
  "水晶靴": {
    "ITEM_MODIFYDEFENCE": [
      54,
      72
    ],
    "ITEM_RSS": [
      21,
      35
    ]
  },
  "銀靴": {
    "ITEM_MODIFYDEFENCE": [
      50,
      67
    ]
  },
  "芙蕾雅之靴": {
    "ITEM_MODIFYCRITICAL": [
      2,
      6
    ],
    "ITEM_MODIFYCOUNTER": [
      2,
      6
    ]
  },
  "流水之靴": {
    "ITEM_MODIFYDEFENCE": [
      61,
      81
    ],
    "ITEM_RSS": [
      24,
      40
    ]
  },
  "標準長靴+": {
    "ITEM_RSS": [
      8,
      24
    ],
    "ITEM_MODIFYDEFENCE": [
      55,
      75
    ],
    "ITEM_MODIFYAVOID": [
      -1,
      5
    ]
  },
  "鑽石長靴": {
    "ITEM_MODIFYCOUNTER": [
      1,
      5
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ],
    "ITEM_MODIFYHITRATE": [
      0,
      4
    ]
  },
  "鑽石靴": {
    "ITEM_MODIFYDEFENCE": [
      78,
      91
    ],
    "ITEM_RSS": [
      27,
      45
    ]
  },
  "秘密之靴": {
    "ITEM_MODIFYDEFENCE": [
      85,
      100
    ],
    "ITEM_RSS": [
      40,
      50
    ]
  },
  "龍之靴": {
    "ITEM_MODIFYAVOID": [
      1,
      5
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ]
  },
  "幸運靴": {
    "ITEM_RSS": [
      20,
      25
    ],
    "ITEM_MODIFYDEFENCE": [
      80,
      90
    ],
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "試力鞋": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_RSS": [
      50,
      60
    ],
    "ITEM_MODIFYDEFENCE": [
      100,
      120
    ]
  },
  "威力短弓": {
    "ITEM_MODIFYATTACK": [
      17,
      33
    ]
  },
  "輕型弓": {
    "ITEM_MODIFYATTACK": [
      11,
      22
    ]
  },
  "短戰弓": {
    "ITEM_MODIFYATTACK": [
      24,
      44
    ]
  },
  "獵弓": {
    "ITEM_MODIFYATTACK": [
      30,
      55
    ]
  },
  "格鬥弓": {
    "ITEM_MODIFYATTACK": [
      46,
      77
    ]
  },
  "強弓": {
    "ITEM_MODIFYATTACK": [
      40,
      66
    ]
  },
  "狙擊弓": {
    "ITEM_MODIFYATTACK": [
      57,
      88
    ]
  },
  "超強狙擊弓": {
    "ITEM_MODIFYATTACK": [
      64,
      99
    ]
  },
  "米斯特汀之弓": {
    "ITEM_MODIFYAVOID": [
      1,
      3
    ],
    "ITEM_MODIFYATTACK": [
      75,
      123
    ]
  },
  "殺手長弓": {
    "ITEM_MODIFYATTACK": [
      77,
      110
    ]
  },
  "衝擊弓": {
    "ITEM_MODIFYATTACK": [
      85,
      121
    ]
  },
  "巨弓": {
    "ITEM_MODIFYATTACK": [
      99,
      132
    ]
  },
  "長格鬥弓": {
    "ITEM_MODIFYATTACK": [
      107,
      143
    ]
  },
  "月光長弓": {
    "ITEM_MODIFYATTACK": [
      124,
      165
    ]
  },
  "破邪長弓": {
    "ITEM_MODIFYHITRATE": [
      8,
      12
    ],
    "ITEM_MODIFYCRITICAL": [
      0,
      4
    ],
    "ITEM_MODIFYATTACK": [
      120,
      130
    ]
  },
  "月光長弓+": {
    "ITEM_MODIFYATTACK": [
      130,
      160
    ],
    "ITEM_MODIFYHITRATE": [
      -1,
      7
    ]
  },
  "重弦弓": {
    "ITEM_MODIFYATTACK": [
      140,
      187
    ]
  },
  "原始石弓": {
    "ITEM_MODIFYATTACK": [
      170,
      187
    ],
    "ITEM_MODIFYHITRATE": [
      13,
      17
    ]
  },
  "平行弓": {
    "ITEM_MODIFYATTACK": [
      167,
      209
    ]
  },
  "摘星之弓": {
    "ITEM_MODIFYATTACK": [
      196,
      231
    ]
  },
  "魔彈": {
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "月之弓": {
    "ITEM_MODIFYHITRATE": [
      6,
      10
    ],
    "ITEM_MODIFYATTACK": [
      222,
      250
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "調和之弓": {
    "ITEM_MODIFYCRITICAL": [
      4,
      8
    ],
    "ITEM_MODIFYATTACK": [
      180,
      230
    ],
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "狂怒繃帶": {
    "ITEM_MODIFYHITRATE": [
      1,
      10
    ],
    "ITEM_MODIFYCRITICAL": [
      5,
      15
    ],
    "ITEM_MODIFYATTACK": [
      20,
      40
    ]
  },
  "保護衣": {
    "ITEM_MODIFYDEFENCE": [
      11,
      21
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "旅人之服": {
    "ITEM_MODIFYDEFENCE": [
      7,
      14
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "皮裝": {
    "ITEM_MODIFYDEFENCE": [
      19,
      35
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "羽毛裝": {
    "ITEM_MODIFYDEFENCE": [
      15,
      28
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "硬皮服": {
    "ITEM_MODIFYDEFENCE": [
      25,
      42
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "鎖鏈裝": {
    "ITEM_MODIFYDEFENCE": [
      29,
      49
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "布甲": {
    "ITEM_MODIFYDEFENCE": [
      36,
      56
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "襯甲": {
    "ITEM_MODIFYDEFENCE": [
      41,
      63
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "士兵護衣": {
    "ITEM_MODIFYDEFENCE": [
      54,
      77
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "功夫裝": {
    "ITEM_MODIFYDEFENCE": [
      38,
      48
    ],
    "ITEM_RSS": [
      15,
      18
    ]
  },
  "環服": {
    "ITEM_MODIFYDEFENCE": [
      49,
      70
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "長索錐衣": {
    "ITEM_MODIFYDEFENCE": [
      63,
      84
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "索錐上衣": {
    "ITEM_MODIFYDEFENCE": [
      68,
      91
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "骨衣": {
    "ITEM_MODIFYDEFENCE": [
      79,
      105
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "超級衣服": {
    "ITEM_MODIFYDEFENCE": [
      74,
      98
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "步兵戰衣": {
    "ITEM_MODIFYDEFENCE": [
      89,
      119
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "疾風之衣": {
    "ITEM_MODIFYHITRATE": [
      0,
      4
    ],
    "ITEM_MODIFYDEFENCE": [
      100,
      112
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "獸骨之衣+": {
    "ITEM_MODIFYAGILITY": [
      10,
      20
    ],
    "ITEM_MODIFYDEFENCE": [
      88,
      115
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "女神之衣": {
    "ITEM_MODIFYAVOID": [
      13,
      17
    ],
    "ITEM_MODIFYHITRATE": [
      0,
      4
    ]
  },
  "勇者之衣": {
    "ITEM_MODIFYDEFENCE": [
      116,
      133
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "不死鳥之服": {
    "ITEM_MODIFYDEFENCE": [
      135,
      147
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "靈魂之服": {
    "ITEM_MODIFYAVOID": [
      3,
      7
    ],
    "ITEM_MODIFYHITRATE": [
      0,
      4
    ]
  },
  "幻想之服": {
    "ITEM_MODIFYDEFENCE": [
      90,
      110
    ],
    "ITEM_MODIFYCRITICAL": [
      3,
      7
    ]
  },
  "海洋之服": {
    "ITEM_MODIFYDEFENCE": [
      156,
      190
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "小刀": {
    "ITEM_MODIFYATTACK": [
      9,
      18
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "銳刃小刀": {
    "ITEM_MODIFYATTACK": [
      14,
      27
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "細刃擲刀": {
    "ITEM_MODIFYATTACK": [
      25,
      45
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "圓盤小刀": {
    "ITEM_MODIFYATTACK": [
      20,
      36
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "細直刃小刀": {
    "ITEM_MODIFYATTACK": [
      38,
      63
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "滑翔小刀": {
    "ITEM_MODIFYATTACK": [
      32,
      54
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "耳柄小刀": {
    "ITEM_MODIFYATTACK": [
      47,
      72
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "騎士小刀": {
    "ITEM_MODIFYATTACK": [
      53,
      81
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "忍者飛鏢": {
    "ITEM_MODIFYAGILITY": [
      1,
      6
    ],
    "ITEM_MODIFYATTACK": [
      65,
      110
    ]
  },
  "球鍔小刀": {
    "ITEM_MODIFYATTACK": [
      63,
      90
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "雙刃小刀": {
    "ITEM_MODIFYATTACK": [
      69,
      99
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "闊刃小刀": {
    "ITEM_MODIFYATTACK": [
      81,
      108
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "觸角小刀": {
    "ITEM_MODIFYATTACK": [
      88,
      117
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "兇殺刀": {
    "ITEM_MODIFYATTACK": [
      101,
      135
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "漢拉提小刀": {
    "ITEM_MODIFYHITRATE": [
      13,
      17
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      116,
      126
    ],
    "ITEM_MODIFYAVOID": [
      -17,
      -13
    ]
  },
  "切肉小刀": {
    "ITEM_MODIFYHITRATE": [
      13,
      17
    ],
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ],
    "ITEM_MODIFYAVOID": [
      13,
      17
    ]
  },
  "古傳小刀": {
    "ITEM_MODIFYATTACK": [
      115,
      153
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "疾速短刀+": {
    "ITEM_MODIFYHITRATE": [
      -1,
      5
    ],
    "ITEM_MODIFYCRITICAL": [
      -1,
      7
    ],
    "ITEM_MODIFYATTACK": [
      110,
      140
    ]
  },
  "手裡劍": {
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYCRITICAL": [
      4,
      8
    ],
    "ITEM_MODIFYATTACK": [
      117,
      151
    ]
  },
  "華麗小刀": {
    "ITEM_MODIFYATTACK": [
      137,
      171
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "勾爪擲刀": {
    "ITEM_MODIFYATTACK": [
      161,
      189
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      5
    ]
  },
  "幻之匕首": {
    "ITEM_MODIFYATTACK": [
      190,
      210
    ],
    "ITEM_MODIFYCRITICAL": [
      -5,
      -1
    ]
  },
  "兇殘刀": {
    "ITEM_MODIFYHITRATE": [
      2,
      4
    ],
    "ITEM_MODIFYCRITICAL": [
      14,
      16
    ],
    "ITEM_MODIFYATTACK": [
      216,
      240
    ]
  },
  "破滅刀": {
    "ITEM_MODIFYHITRATE": [
      12,
      14
    ],
    "ITEM_MODIFYCRITICAL": [
      2,
      4
    ],
    "ITEM_MODIFYATTACK": [
      216,
      244
    ],
    "ITEM_MODIFYAVOID": [
      3,
      7
    ]
  },
  "弗旦之盾": {
    "ITEM_RSS": [
      30,
      43
    ]
  },
  "弗旦之盾+": {
    "ITEM_MODIFYFORCEPOINT": [
      50,
      65
    ]
  },
  "弗旦之袍": {
    "ITEM_MODIFYFORCEPOINT": [
      341,
      432
    ],
    "ITEM_MODIFYDEFENCE": [
      47,
      67
    ],
    "ITEM_ADM": [
      -1,
      1
    ]
  },
  "弗旦之袍+": {
    "ITEM_MODIFYDEFENCE": [
      47,
      67
    ],
    "ITEM_MODIFYATTACK": [
      93,
      180
    ]
  },
  "弗旦衣": {
    "ITEM_MODIFYDEFENCE": [
      80,
      120
    ]
  },
  "弗旦帽": {
    "ITEM_MODIFYDEFENCE": [
      32,
      45
    ]
  },
  "弗旦帽+": {
    "ITEM_MODIFYRECOVERY": [
      10,
      20
    ]
  },
  "弗旦鞋": {
    "ITEM_MODIFYDEFENCE": [
      20,
      24
    ],
    "ITEM_MODIFYAGILITY": [
      -3,
      10
    ]
  },
  "弗旦鞋+": {
    "ITEM_MODIFYAGILITY": [
      20,
      24
    ],
    "ITEM_MODIFYMAGIC": [
      -2,
      10
    ]
  },
  "弗旦頭盔": {
    "ITEM_MODIFYDEFENCE": [
      70,
      92
    ],
    "ITEM_RSS": [
      30,
      46
    ]
  },
  "弗旦頭盔+": {
    "ITEM_MODIFYAGILITY": [
      20,
      30
    ]
  },
  "弗旦鎧": {
    "ITEM_RSS": [
      23,
      34
    ],
    "ITEM_MODIFYAGILITY": [
      -3,
      5
    ],
    "ITEM_MODIFYDEFENCE": [
      132,
      172
    ]
  },
  "弗旦鎧+": {
    "ITEM_MODIFYFORCEPOINT": [
      203,
      300
    ]
  },
  "麻布帽": {
    "ITEM_MODIFYDEFENCE": [
      4,
      7
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "硬帽": {
    "ITEM_MODIFYDEFENCE": [
      6,
      11
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "皮帽": {
    "ITEM_MODIFYDEFENCE": [
      10,
      18
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "輕帽": {
    "ITEM_MODIFYDEFENCE": [
      8,
      14
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "可愛的帽子": {
    "ITEM_MODIFYDEFENCE": [
      15,
      25
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "硬皮帽": {
    "ITEM_MODIFYDEFENCE": [
      13,
      21
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "時髦帽子": {
    "ITEM_MODIFYDEFENCE": [
      18,
      28
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "鴨舌帽": {
    "ITEM_MODIFYDEFENCE": [
      21,
      32
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "高級帽子": {
    "ITEM_MODIFYDEFENCE": [
      27,
      39
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "劍客帽": {
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ],
    "ITEM_MODIFYHP": [
      65,
      75
    ],
    "ITEM_MODIFYDEFENCE": [
      10,
      14
    ],
    "ITEM_MODIFYAVOID": [
      1,
      5
    ]
  },
  "藍徽章之帽": {
    "ITEM_MODIFYDEFENCE": [
      25,
      35
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "青銅帽子": {
    "ITEM_MODIFYDEFENCE": [
      35,
      46
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "裝飾著花的帽子": {
    "ITEM_MODIFYDEFENCE": [
      32,
      42
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "可愛的扁帽子": {
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ],
    "ITEM_MODIFYDEFENCE": [
      38,
      45
    ],
    "ITEM_MODIFYAVOID": [
      -1,
      5
    ]
  },
  "軍帽": {
    "ITEM_MODIFYDEFENCE": [
      42,
      56
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "時髦避暑帽": {
    "ITEM_MODIFYDEFENCE": [
      32,
      46
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "頭目帽子": {
    "ITEM_MODIFYAVOID": [
      1,
      5
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "羽毛帽": {
    "ITEM_MODIFYDEFENCE": [
      54,
      67
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "魔術師之帽": {
    "ITEM_MODIFYHITRATE": [
      13,
      17
    ]
  },
  "妖精之帽": {
    "ITEM_MODIFYAVOID": [
      0,
      4
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "黃昏之帽": {
    "ITEM_MODIFYDEFENCE": [
      63,
      74
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "貝斯神帽": {
    "ITEM_MODIFYDEFENCE": [
      35,
      50
    ],
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "神官帽": {
    "ITEM_MODIFYDEFENCE": [
      60,
      90
    ],
    "ITEM_MODIFYHITRATE": [
      8,
      12
    ]
  },
  "受詛咒的薑餅人": {
    "ITEM_MODIFYAGILITY": [
      10,
      20
    ],
    "ITEM_MODIFYDEFENCE": [
      10,
      20
    ],
    "ITEM_MODIFYAVOID": [
      5,
      15
    ]
  },
  "硬皮頭盔": {
    "ITEM_MODIFYDEFENCE": [
      6,
      11
    ],
    "ITEM_RSS": [
      5,
      7
    ]
  },
  "銅製頭盔": {
    "ITEM_MODIFYDEFENCE": [
      9,
      17
    ],
    "ITEM_RSS": [
      3,
      5
    ]
  },
  "銅鐵皮盔": {
    "ITEM_MODIFYDEFENCE": [
      15,
      28
    ],
    "ITEM_RSS": [
      6,
      10
    ]
  },
  "鐵板布盔": {
    "ITEM_MODIFYDEFENCE": [
      12,
      22
    ],
    "ITEM_RSS": [
      10,
      14
    ]
  },
  "金屬護額": {
    "ITEM_MODIFYDEFENCE": [
      20,
      33
    ],
    "ITEM_RSS": [
      15,
      21
    ]
  },
  "鐵製頭盔": {
    "ITEM_MODIFYDEFENCE": [
      23,
      39
    ],
    "ITEM_RSS": [
      9,
      15
    ]
  },
  "角飾頭盔": {
    "ITEM_MODIFYDEFENCE": [
      33,
      50
    ],
    "ITEM_RSS": [
      12,
      20
    ]
  },
  "霸葛頭盔": {
    "ITEM_MODIFYDEFENCE": [
      29,
      44
    ],
    "ITEM_RSS": [
      20,
      28
    ]
  },
  "開放式頭盔": {
    "ITEM_MODIFYDEFENCE": [
      39,
      55
    ],
    "ITEM_RSS": [
      25,
      35
    ]
  },
  "聖騎士之盔": {
    "ITEM_MODIFYDEFENCE": [
      42,
      52
    ],
    "ITEM_RSS": [
      35,
      40
    ]
  },
  "葛理克頭盔": {
    "ITEM_MODIFYDEFENCE": [
      43,
      61
    ],
    "ITEM_RSS": [
      15,
      25
    ]
  },
  "巴比克頭盔": {
    "ITEM_MODIFYDEFENCE": [
      50,
      66
    ],
    "ITEM_RSS": [
      30,
      42
    ]
  },
  "利刃頭盔": {
    "ITEM_MODIFYDEFENCE": [
      54,
      72
    ],
    "ITEM_RSS": [
      18,
      30
    ]
  },
  "鋼製頭盔": {
    "ITEM_MODIFYDEFENCE": [
      62,
      83
    ],
    "ITEM_RSS": [
      24,
      38
    ]
  },
  "騎士頭盔": {
    "ITEM_RSS": [
      28,
      42
    ]
  },
  "博流蓋爾頭盔": {
    "ITEM_MODIFYAVOID": [
      23,
      27
    ],
    "ITEM_MODIFYHITRATE": [
      -7,
      -3
    ]
  },
  "鉚釘頭盔": {
    "ITEM_MODIFYDEFENCE": [
      71,
      94
    ],
    "ITEM_RSS": [
      32,
      48
    ]
  },
  "鋼製頭盔+": {
    "ITEM_RSS": [
      16,
      32
    ],
    "ITEM_MODIFYHITRATE": [
      -3,
      1
    ],
    "ITEM_MODIFYDEFENCE": [
      65,
      85
    ],
    "ITEM_MODIFYAVOID": [
      -1,
      7
    ]
  },
  "羽毛頭盔": {
    "ITEM_MODIFYDEFENCE": [
      84,
      105
    ],
    "ITEM_RSS": [
      45,
      63
    ]
  },
  "龍盔": {
    "ITEM_RSS": [
      24,
      36
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ]
  },
  "白金頭盔": {
    "ITEM_MODIFYDEFENCE": [
      99,
      116
    ],
    "ITEM_RSS": [
      50,
      70
    ]
  },
  "聖龍頭盔": {
    "ITEM_MODIFYCRITICAL": [
      -7,
      -3
    ],
    "ITEM_RSS": [
      40,
      60
    ]
  },
  "正義頭盔": {
    "ITEM_RSS": [
      77,
      87
    ],
    "ITEM_MODIFYCRITICAL": [
      4,
      8
    ],
    "ITEM_MODIFYDEFENCE": [
      93,
      103
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "靈力頭盔": {
    "ITEM_MODIFYCOUNTER": [
      6,
      10
    ],
    "ITEM_RSS": [
      67,
      77
    ],
    "ITEM_MODIFYHITRATE": [
      2,
      6
    ],
    "ITEM_MODIFYDEFENCE": [
      100,
      120
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "屈原的戒指": {
    "ITEM_MODIFYDEFENCE": [
      1,
      30
    ],
    "ITEM_MODIFYAVOID": [
      1,
      20
    ],
    "ITEM_MODIFYATTACK": [
      1,
      30
    ],
    "ITEM_MODIFYCRITICAL": [
      1,
      20
    ],
    "ITEM_MODIFYMAGIC": [
      1,
      30
    ],
    "ITEM_RSS": [
      1,
      30
    ]
  },
  "聖域星戒": {
    "ITEM_MODIFYRECOVERY": [
      15,
      25
    ],
    "ITEM_MODIFYHP": [
      60,
      120
    ],
    "ITEM_MODIFYAVOID": [
      5,
      15
    ],
    "ITEM_MODIFYHITRATE": [
      5,
      15
    ],
    "ITEM_MODIFYMAGIC": [
      15,
      25
    ],
    "ITEM_MODIFYATTACK": [
      30,
      50
    ],
    "ITEM_MODIFYDEFENCE": [
      30,
      50
    ],
    "ITEM_MODIFYCOUNTER": [
      5,
      15
    ],
    "ITEM_MODIFYAGILITY": [
      30,
      50
    ],
    "ITEM_MODIFYCRITICAL": [
      5,
      15
    ]
  },
  "弗旦之戒": {
    "ITEM_ADM": [
      1,
      3
    ],
    "ITEM_MODIFYRECOVERY": [
      10,
      20
    ],
    "ITEM_MODIFYMAGIC": [
      10,
      20
    ]
  },
  "弗旦之戒+": {
    "ITEM_MODIFYATTACK": [
      27,
      38
    ],
    "ITEM_RSS": [
      7,
      10
    ],
    "ITEM_MODIFYRECOVERY": [
      10,
      14
    ]
  },
  "羽毛袍": {
    "ITEM_MODIFYDEFENCE": [
      4,
      8
    ]
  },
  "輕皮袍": {
    "ITEM_MODIFYDEFENCE": [
      6,
      12
    ]
  },
  "風袍": {
    "ITEM_MODIFYDEFENCE": [
      11,
      20
    ]
  },
  "網袍": {
    "ITEM_MODIFYDEFENCE": [
      9,
      16
    ]
  },
  "硬皮袍": {
    "ITEM_MODIFYDEFENCE": [
      14,
      24
    ]
  },
  "環袍": {
    "ITEM_MODIFYDEFENCE": [
      17,
      28
    ]
  },
  "月亮之袍": {
    "ITEM_MODIFYDEFENCE": [
      23,
      36
    ]
  },
  "狐皮披風": {
    "ITEM_MODIFYAGILITY": [
      4,
      12
    ],
    "ITEM_MODIFYDEFENCE": [
      16,
      24
    ]
  },
  "烏鴉之袍": {
    "ITEM_MODIFYDEFENCE": [
      21,
      32
    ]
  },
  "東方法衣": {
    "ITEM_MODIFYDEFENCE": [
      28,
      40
    ]
  },
  "治癒之袍": {
    "ITEM_MODIFYDEFENCE": [
      68,
      75
    ]
  },
  "聖堂之袍": {
    "ITEM_MODIFYDEFENCE": [
      31,
      44
    ]
  },
  "聖者之袍": {
    "ITEM_MODIFYDEFENCE": [
      36,
      48
    ]
  },
  "戰鬥長袍": {
    "ITEM_MODIFYDEFENCE": [
      39,
      52
    ]
  },
  "冠軍之袍": {
    "ITEM_MODIFYDEFENCE": [
      42,
      56
    ]
  },
  "時之袍": {
    "ITEM_MODIFYDEFENCE": [
      45,
      60
    ]
  },
  "死神之袍": {
    "ITEM_MODIFYDEFENCE": [
      48,
      64
    ]
  },
  "勇者之袍": {
    "ITEM_MODIFYDEFENCE": [
      51,
      68
    ]
  },
  "潔淨之袍+": {
    "ITEM_MODIFYDEFENCE": [
      45,
      61
    ],
    "ITEM_MODIFYRECOVERY": [
      1,
      5
    ]
  },
  "黑暗之袍": {
    "ITEM_MODIFYDEFENCE": [
      61,
      76
    ]
  },
  "靈魂之袍": {
    "ITEM_MODIFYDEFENCE": [
      71,
      84
    ]
  },
  "共鳴之袍": {
    "ITEM_MODIFYDEFENCE": [
      25,
      35
    ],
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "和平之袍": {
    "ITEM_MODIFYDEFENCE": [
      111,
      121
    ],
    "ITEM_MODIFYCRITICAL": [
      8,
      12
    ]
  },
  "小型盾": {
    "ITEM_RSS": [
      8,
      10
    ],
    "ITEM_MODIFYDEFENCE": [
      9,
      17
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "小圓盾": {
    "ITEM_RSS": [
      10,
      12
    ],
    "ITEM_MODIFYDEFENCE": [
      6,
      11
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "板盾": {
    "ITEM_RSS": [
      20,
      24
    ],
    "ITEM_MODIFYDEFENCE": [
      12,
      22
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "鳶盾": {
    "ITEM_RSS": [
      16,
      20
    ],
    "ITEM_MODIFYDEFENCE": [
      15,
      28
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "哥特盾": {
    "ITEM_RSS": [
      24,
      30
    ],
    "ITEM_MODIFYDEFENCE": [
      23,
      39
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "漩渦重盾": {
    "ITEM_RSS": [
      30,
      36
    ],
    "ITEM_MODIFYDEFENCE": [
      20,
      33
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "士兵盾": {
    "ITEM_RSS": [
      40,
      48
    ],
    "ITEM_MODIFYDEFENCE": [
      29,
      44
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "重盾": {
    "ITEM_RSS": [
      32,
      40
    ],
    "ITEM_MODIFYDEFENCE": [
      33,
      50
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "反光之盾": {
    "ITEM_RSS": [
      40,
      50
    ],
    "ITEM_MODIFYDEFENCE": [
      43,
      61
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "聖者之盾": {
    "ITEM_RSS": [
      50,
      55
    ],
    "ITEM_MODIFYDEFENCE": [
      26,
      29
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "蜥蝪盾": {
    "ITEM_RSS": [
      50,
      60
    ],
    "ITEM_MODIFYDEFENCE": [
      39,
      55
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "風之盾": {
    "ITEM_RSS": [
      60,
      72
    ],
    "ITEM_MODIFYDEFENCE": [
      50,
      66
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "獅子盾": {
    "ITEM_RSS": [
      48,
      60
    ],
    "ITEM_MODIFYDEFENCE": [
      54,
      72
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "防守之盾": {
    "ITEM_RSS": [
      70,
      84
    ],
    "ITEM_MODIFYDEFENCE": [
      58,
      77
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "黃金之盾": {
    "ITEM_MODIFYHITRATE": [
      -12,
      -8
    ],
    "ITEM_MODIFYDEFENCE": [
      82,
      103
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "力量之盾": {
    "ITEM_MODIFYAVOID": [
      6,
      10
    ],
    "ITEM_RSS": [
      32,
      40
    ]
  },
  "防御之盾+": {
    "ITEM_MODIFYDEFENCE": [
      59,
      79
    ],
    "ITEM_RSS": [
      64,
      80
    ],
    "ITEM_MODIFYATTACK": [
      5,
      20
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "鏡之盾": {
    "ITEM_RSS": [
      80,
      96
    ],
    "ITEM_MODIFYDEFENCE": [
      66,
      88
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "火龍之盾": {
    "ITEM_RSS": [
      36,
      45
    ],
    "ITEM_MODIFYHITRATE": [
      0,
      4
    ],
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "漆黑之盾": {
    "ITEM_RSS": [
      90,
      108
    ],
    "ITEM_MODIFYDEFENCE": [
      84,
      105
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "黑暗之盾": {
    "ITEM_MODIFYDEFENCE": [
      99,
      116
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "突猛盾": {
    "ITEM_RSS": [
      90,
      100
    ],
    "ITEM_MODIFYHITRATE": [
      6,
      10
    ],
    "ITEM_MODIFYDEFENCE": [
      119,
      136
    ],
    "ITEM_MODIFYAVOID": [
      -12,
      -8
    ]
  },
  "重型防禦盾": {
    "ITEM_RSS": [
      135,
      145
    ],
    "ITEM_MODIFYCRITICAL": [
      4,
      8
    ],
    "ITEM_MODIFYDEFENCE": [
      96,
      106
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "馬車鞋": {
    "ITEM_MODIFYDEFENCE": [
      3,
      5
    ],
    "ITEM_MODIFYAGILITY": [
      5,
      6
    ]
  },
  "運動鞋": {
    "ITEM_MODIFYDEFENCE": [
      2,
      3
    ],
    "ITEM_MODIFYAGILITY": [
      3,
      4
    ]
  },
  "皮鞋": {
    "ITEM_MODIFYDEFENCE": [
      3,
      6
    ],
    "ITEM_MODIFYAGILITY": [
      6,
      8
    ]
  },
  "安全鞋": {
    "ITEM_MODIFYDEFENCE": [
      4,
      8
    ],
    "ITEM_MODIFYAGILITY": [
      8,
      10
    ]
  },
  "光之鞋": {
    "ITEM_MODIFYDEFENCE": [
      5,
      9
    ],
    "ITEM_MODIFYAGILITY": [
      10,
      12
    ]
  },
  "戰鞋": {
    "ITEM_MODIFYDEFENCE": [
      7,
      11
    ],
    "ITEM_MODIFYAGILITY": [
      11,
      14
    ]
  },
  "薄板鞋": {
    "ITEM_MODIFYDEFENCE": [
      8,
      12
    ],
    "ITEM_MODIFYAGILITY": [
      13,
      16
    ]
  },
  "鎖鏈鞋": {
    "ITEM_MODIFYDEFENCE": [
      9,
      14
    ],
    "ITEM_MODIFYAGILITY": [
      14,
      18
    ]
  },
  "特製舞鞋": {
    "ITEM_MODIFYDEFENCE": [
      13,
      15
    ],
    "ITEM_MODIFYAGILITY": [
      19,
      21
    ]
  },
  "維京鞋": {
    "ITEM_MODIFYDEFENCE": [
      12,
      17
    ],
    "ITEM_MODIFYAGILITY": [
      18,
      22
    ]
  },
  "蜥蝪鞋": {
    "ITEM_MODIFYDEFENCE": [
      11,
      15
    ],
    "ITEM_MODIFYAGILITY": [
      16,
      20
    ]
  },
  "戰鬥鞋": {
    "ITEM_MODIFYDEFENCE": [
      14,
      18
    ],
    "ITEM_MODIFYAGILITY": [
      19,
      24
    ]
  },
  "騎士鞋": {
    "ITEM_MODIFYDEFENCE": [
      15,
      20
    ],
    "ITEM_MODIFYAGILITY": [
      21,
      26
    ]
  },
  "妖精鞋": {
    "ITEM_MODIFYDEFENCE": [
      17,
      23
    ],
    "ITEM_MODIFYAGILITY": [
      24,
      30
    ]
  },
  "紫水晶鞋": {
    "ITEM_MODIFYDEFENCE": [
      44,
      54
    ]
  },
  "白金鞋": {
    "ITEM_MODIFYDEFENCE": [
      20,
      26
    ],
    "ITEM_MODIFYAGILITY": [
      26,
      32
    ]
  },
  "妖精鞋+": {
    "ITEM_MODIFYAGILITY": [
      34,
      40
    ],
    "ITEM_MODIFYDEFENCE": [
      18,
      24
    ]
  },
  "精緻高根鞋": {
    "ITEM_MODIFYDEFENCE": [
      20,
      26
    ]
  },
  "神秘之鞋": {
    "ITEM_MODIFYDEFENCE": [
      23,
      29
    ],
    "ITEM_MODIFYAGILITY": [
      30,
      38
    ]
  },
  "黃金鞋": {
    "ITEM_MODIFYDEFENCE": [
      27,
      32
    ],
    "ITEM_MODIFYAGILITY": [
      36,
      42
    ]
  },
  "龍之鞋": {
    "ITEM_MODIFYAGILITY": [
      31,
      37
    ],
    "ITEM_MODIFYDEFENCE": [
      37,
      42
    ],
    "ITEM_MODIFYAVOID": [
      1,
      5
    ]
  },
  "大木屐": {
    "ITEM_MODIFYAGILITY": [
      10,
      13
    ],
    "ITEM_MODIFYCRITICAL": [
      4,
      8
    ],
    "ITEM_MODIFYDEFENCE": [
      48,
      68
    ]
  },
  "守護之鞋": {
    "ITEM_MODIFYAGILITY": [
      45,
      64
    ],
    "ITEM_MODIFYDEFENCE": [
      10,
      15
    ],
    "ITEM_MODIFYAVOID": [
      13,
      17
    ]
  },
  "攻城槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      15,
      30
    ]
  },
  "短矛": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      10,
      20
    ]
  },
  "刺槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      22,
      40
    ]
  },
  "金屬槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      28,
      50
    ]
  },
  "長柄尖槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      42,
      70
    ]
  },
  "長柄彎槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      36,
      60
    ]
  },
  "穗槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      52,
      80
    ]
  },
  "雙叉戟": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      59,
      90
    ]
  },
  "偃月刀": {
    "ITEM_MODIFYDEFENCE": [
      1,
      4
    ],
    "ITEM_MODIFYATTACK": [
      75,
      118
    ]
  },
  "騎士槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      77,
      110
    ]
  },
  "護衛槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      70,
      100
    ]
  },
  "大砍槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      90,
      120
    ]
  },
  "長尖槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      98,
      130
    ]
  },
  "雙刃槍": {
    "ITEM_MODIFYCOUNTER": [
      10,
      14
    ],
    "ITEM_MODIFYHITRATE": [
      4,
      8
    ],
    "ITEM_MODIFYATTACK": [
      120,
      125
    ]
  },
  "蠍槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      105,
      140
    ]
  },
  "東方長刺鎗": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      6,
      10
    ],
    "ITEM_MODIFYAVOID": [
      -6,
      -2
    ]
  },
  "闊刃槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      120,
      160
    ]
  },
  "蠍槍+": {
    "ITEM_MODIFYCOUNTER": [
      3,
      9
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      7
    ],
    "ITEM_MODIFYATTACK": [
      110,
      148
    ]
  },
  "原始槍": {
    "ITEM_MODIFYCOUNTER": [
      7,
      11
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ],
    "ITEM_MODIFYATTACK": [
      180,
      190
    ],
    "ITEM_MODIFYAVOID": [
      -5,
      -1
    ]
  },
  "鉤爪槍": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      152,
      190
    ]
  },
  "三叉戰戟": {
    "ITEM_MODIFYCOUNTER": [
      4,
      8
    ],
    "ITEM_MODIFYHITRATE": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      179,
      210
    ]
  },
  "異型槍": {
    "ITEM_MODIFYCOUNTER": [
      -1,
      3
    ],
    "ITEM_MODIFYHITRATE": [
      -1,
      3
    ],
    "ITEM_MODIFYAVOID": [
      -6,
      -2
    ]
  },
  "穿刺槍": {
    "ITEM_MODIFYATTACK": [
      225,
      250
    ],
    "ITEM_MODIFYHITRATE": [
      14,
      18
    ]
  },
  "痛擊槍": {
    "ITEM_MODIFYCOUNTER": [
      6,
      10
    ],
    "ITEM_MODIFYCRITICAL": [
      6,
      10
    ],
    "ITEM_MODIFYATTACK": [
      206,
      230
    ]
  },
  "短杖": {
    "ITEM_MODIFYMAGIC": [
      4,
      5
    ],
    "ITEM_ADM": [
      11,
      14
    ]
  },
  "權杖": {
    "ITEM_MODIFYATTACK": [
      5,
      10
    ],
    "ITEM_ADM": [
      11,
      12
    ]
  },
  "大地之杖": {
    "ITEM_MODIFYMAGIC": [
      8,
      10
    ],
    "ITEM_ADM": [
      42,
      48
    ]
  },
  "激流權杖": {
    "ITEM_MODIFYATTACK": [
      11,
      20
    ],
    "ITEM_ADM": [
      42,
      45
    ]
  },
  "魔之手杖": {
    "ITEM_MODIFYMAGIC": [
      10,
      15
    ],
    "ITEM_ADM": [
      73,
      82
    ]
  },
  "魔之權杖": {
    "ITEM_MODIFYATTACK": [
      18,
      30
    ],
    "ITEM_ADM": [
      73,
      77
    ]
  },
  "賢者手杖": {
    "ITEM_MODIFYMAGIC": [
      16,
      20
    ],
    "ITEM_ADM": [
      104,
      116
    ]
  },
  "賢者權杖": {
    "ITEM_MODIFYATTACK": [
      26,
      40
    ],
    "ITEM_ADM": [
      104,
      110
    ]
  },
  "琥珀杖": {
    "ITEM_MODIFYMAGIC": [
      20,
      25
    ],
    "ITEM_ADM": [
      135,
      150
    ]
  },
  "琥珀權杖": {
    "ITEM_MODIFYATTACK": [
      35,
      50
    ],
    "ITEM_ADM": [
      135,
      142
    ]
  },
  "魔晶之杖": {
    "ITEM_ADM": [
      135,
      142
    ],
    "ITEM_MODIFYRECOVERY": [
      1,
      6
    ],
    "ITEM_MODIFYATTACK": [
      38,
      53
    ]
  },
  "元素之杖": {
    "ITEM_MODIFYMAGIC": [
      24,
      30
    ],
    "ITEM_ADM": [
      166,
      184
    ]
  },
  "神聖之杖": {
    "ITEM_MODIFYATTACK": [
      45,
      60
    ],
    "ITEM_ADM": [
      166,
      175
    ]
  },
  "怒音之杖": {
    "ITEM_MODIFYMAGIC": [
      28,
      35
    ],
    "ITEM_ADM": [
      197,
      218
    ]
  },
  "隱者之杖": {
    "ITEM_MODIFYATTACK": [
      53,
      70
    ],
    "ITEM_ADM": [
      197,
      207
    ]
  },
  "光明短杖": {
    "ITEM_MODIFYMAGIC": [
      32,
      40
    ],
    "ITEM_ADM": [
      228,
      252
    ]
  },
  "惡魔之杖": {
    "ITEM_MODIFYATTACK": [
      60,
      80
    ],
    "ITEM_ADM": [
      228,
      240
    ]
  },
  "落雷權杖+": {
    "ITEM_ADM": [
      197,
      208
    ],
    "ITEM_MODIFYMAGIC": [
      28,
      35
    ],
    "ITEM_MODIFYATTACK": [
      50,
      70
    ]
  },
  "天使之杖": {
    "ITEM_MODIFYATTACK": [
      72,
      90
    ],
    "ITEM_ADM": [
      259,
      272
    ]
  },
  "太陽短杖": {
    "ITEM_MODIFYMAGIC": [
      36,
      45
    ],
    "ITEM_ADM": [
      259,
      286
    ]
  },
  "星屑短杖": {
    "ITEM_MODIFYATTACK": [
      85,
      100
    ],
    "ITEM_ADM": [
      290,
      305
    ]
  },
  "聖者之杖": {
    "ITEM_MODIFYMAGIC": [
      43,
      50
    ],
    "ITEM_ADM": [
      290,
      320
    ]
  },
  "王者之手": {
    "ITEM_ADM": [
      324,
      354
    ],
    "ITEM_MODIFYMAGIC": [
      53,
      60
    ],
    "ITEM_MODIFYAVOID": [
      8,
      12
    ]
  },
  "星錘杖": {
    "ITEM_ADM": [
      228,
      252
    ],
    "ITEM_MODIFYHITRATE": [
      8,
      12
    ],
    "ITEM_MODIFYATTACK": [
      130,
      180
    ]
  },
  "長劍": {
    "ITEM_MODIFYATTACK": [
      12,
      24
    ]
  },
  "闊劍": {
    "ITEM_MODIFYATTACK": [
      18,
      36
    ]
  },
  "火舌劍": {
    "ITEM_MODIFYATTACK": [
      33,
      60
    ]
  },
  "突刺劍": {
    "ITEM_MODIFYATTACK": [
      26,
      48
    ]
  },
  "雙手劍": {
    "ITEM_MODIFYATTACK": [
      50,
      84
    ]
  },
  "麵包劍": {
    "ITEM_MODIFYATTACK": [
      43,
      72
    ]
  },
  "鎖刃劍": {
    "ITEM_MODIFYATTACK": [
      70,
      108
    ]
  },
  "雙刃長劍": {
    "ITEM_MODIFYATTACK": [
      62,
      96
    ]
  },
  "長鍔劍": {
    "ITEM_MODIFYATTACK": [
      92,
      132
    ]
  },
  "格鬥劍": {
    "ITEM_MODIFYATTACK": [
      84,
      120
    ]
  },
  "黑作太刀": {
    "ITEM_MODIFYAGILITY": [
      1,
      5
    ],
    "ITEM_MODIFYATTACK": [
      93,
      129
    ]
  },
  "豬牙劍": {
    "ITEM_MODIFYATTACK": [
      108,
      144
    ]
  },
  "雙刃闊劍": {
    "ITEM_MODIFYATTACK": [
      117,
      156
    ]
  },
  "巨劍": {
    "ITEM_MODIFYHITRATE": [
      8,
      12
    ],
    "ITEM_MODIFYATTACK": [
      125,
      170
    ],
    "ITEM_MODIFYAVOID": [
      -7,
      -3
    ]
  },
  "長軍刀": {
    "ITEM_MODIFYATTACK": [
      135,
      180
    ]
  },
  "長軍刀+": {
    "ITEM_MODIFYATTACK": [
      138,
      185
    ]
  },
  "細柄短劍": {
    "ITEM_MODIFYATTACK": [
      153,
      204
    ]
  },
  "護身短劍": {
    "ITEM_MODIFYATTACK": [
      225,
      230
    ]
  },
  "細刃重劍": {
    "ITEM_MODIFYATTACK": [
      182,
      228
    ]
  },
  "青龍刀": {
    "ITEM_MODIFYATTACK": [
      204,
      240
    ]
  },
  "剛毅": {
    "ITEM_MODIFYAVOID": [
      18,
      22
    ],
    "ITEM_MODIFYATTACK": [
      274,
      300
    ]
  },
  "彎勾劍": {
    "ITEM_MODIFYATTACK": [
      224,
      250
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "水龍之弓": {
    "ITEM_MODIFYCRITICAL": [
      0,
      4
    ],
    "ITEM_MODIFYHITRATE": [
      18,
      22
    ]
  },
  "水龍之斧": {
    "ITEM_MODIFYCRITICAL": [
      16,
      20
    ]
  },
  "水龍之服": {
    "ITEM_MODIFYAVOID": [
      58,
      62
    ]
  },
  "水龍之盾": {
    "ITEM_MODIFYCRITICAL": [
      3,
      7
    ],
    "ITEM_MODIFYCOUNTER": [
      3,
      7
    ]
  },
  "水龍之帽": {
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "水龍之靴": {
    "ITEM_MODIFYCRITICAL": [
      3,
      7
    ],
    "ITEM_MODIFYHITRATE": [
      3,
      7
    ]
  },
  "水龍之槍": {
    "ITEM_MODIFYCRITICAL": [
      10,
      14
    ],
    "ITEM_MODIFYHITRATE": [
      4,
      8
    ]
  },
  "水龍之鞋": {
    "ITEM_MODIFYAVOID": [
      0,
      4
    ],
    "ITEM_MODIFYHITRATE": [
      0,
      4
    ]
  },
  "水龍的小刀": {
    "ITEM_MODIFYHITRATE": [
      23,
      27
    ]
  },
  "冰龍": {
    "ITEM_MODIFYCRITICAL": [
      18,
      22
    ]
  }
};

/** Equipment level (the 等級 shown in the guide), by item name. */
export const EQUIPMENT_LEVELS: Record<string, number> = {
  "英靈之誓": 1,
  "洗禮的護符": 10,
  "真・戰符": 10,
  "軟皮甲": 1,
  "護心甲": 1,
  "青銅鎧甲": 2,
  "輕型鎧甲": 2,
  "輕型鎖鍊甲": 3,
  "環甲": 3,
  "金屬皮甲": 4,
  "鋼鐵鎧甲": 4,
  "長型金屬鎧甲": 5,
  "索狀鎧甲": 5,
  "劍齒鎧甲": 5,
  "重鐵板甲": 6,
  "鐵板半身甲": 6,
  "黃金鎧甲": 7,
  "實戰鎧甲": 7,
  "重金屬鎧甲": 8,
  "野獸之鎧": 8,
  "實戰鎧甲+": 8,
  "亡靈鎧甲": 9,
  "帝王之鎧": 9,
  "漆黑之鎧": 10,
  "騎士鎧甲": 10,
  "守護鎧甲": 11,
  "紅繩威鎧": 11,
  "手斧": 1,
  "勇氣之斧": 1,
  "寬手斧": 2,
  "戰鬥手斧": 2,
  "格鬥手斧": 3,
  "鋼斧": 3,
  "長戰斧": 4,
  "雙刃斧": 4,
  "鉤爪斧": 5,
  "闊刃斧": 5,
  "鑽保雷格之斧": 5,
  "大型闊刃斧": 6,
  "彎月大戰斧": 6,
  "大型雙刃斧": 7,
  "超大皇帝斧": 7,
  "大型雙刃斧+": 8,
  "米諾陶斯戰斧": 8,
  "新月斧": 8,
  "薄刃鉤爪斧": 9,
  "彎月長柄斧": 9,
  "金屬重斧": 10,
  "處刑斧": 10,
  "重擊斧": 11,
  "高速斧": 11,
  "木製大型回力鏢": 1,
  "青銅回力鏢": 1,
  "追跡者": 2,
  "彩光回力鏢": 2,
  "殺敵回力鏢": 3,
  "暗殺回力鏢": 3,
  "獅子回力鏢": 4,
  "銳角回力鏢": 4,
  "北斗之鎌刀": 5,
  "阿修塔羅回力鏢": 5,
  "翼鹿回力鏢": 5,
  "蛇獅回力鏢": 6,
  "鶇回力鏢": 6,
  "閃光回力鏢": 7,
  "雄翼牛回力鏢": 7,
  "凶豹回力鏢": 8,
  "赤獅回力鏢": 8,
  "熊翼牛回力鏢+": 8,
  "天使之翼": 9,
  "普利辛回力鏢": 9,
  "天秤回力鏢": 10,
  "治癒回力鏢": 10,
  "基盤飛鏢": 11,
  "節制飛鏢": 11,
  "皮靴": 1,
  "軟皮靴": 1,
  "長靴": 2,
  "硬皮靴": 2,
  "厚底靴": 3,
  "編織的靴子": 3,
  "鎖鍊長靴": 4,
  "鎖鍊靴": 4,
  "防護靴": 5,
  "蜥蝪長靴": 5,
  "蜥蝪靴": 5,
  "鋼靴": 6,
  "鋼製長靴": 6,
  "水晶靴": 7,
  "銀靴": 7,
  "芙蕾雅之靴": 8,
  "流水之靴": 8,
  "標準長靴+": 8,
  "鑽石長靴": 9,
  "鑽石靴": 9,
  "秘密之靴": 10,
  "龍之靴": 10,
  "幸運靴": 11,
  "試力鞋": 11,
  "威力短弓": 1,
  "輕型弓": 1,
  "短戰弓": 2,
  "獵弓": 2,
  "格鬥弓": 3,
  "強弓": 3,
  "狙擊弓": 4,
  "超強狙擊弓": 4,
  "米斯特汀之弓": 5,
  "殺手長弓": 5,
  "衝擊弓": 5,
  "巨弓": 6,
  "長格鬥弓": 6,
  "月光長弓": 7,
  "破邪長弓": 7,
  "月光長弓+": 8,
  "重弦弓": 8,
  "原始石弓": 8,
  "平行弓": 9,
  "摘星之弓": 10,
  "魔彈": 10,
  "月之弓": 11,
  "調和之弓": 11,
  "狂怒繃帶": 1,
  "保護衣": 1,
  "旅人之服": 1,
  "皮裝": 2,
  "羽毛裝": 2,
  "硬皮服": 3,
  "鎖鏈裝": 3,
  "布甲": 4,
  "襯甲": 4,
  "士兵護衣": 5,
  "功夫裝": 5,
  "環服": 5,
  "長索錐衣": 6,
  "索錐上衣": 6,
  "骨衣": 7,
  "超級衣服": 7,
  "步兵戰衣": 8,
  "疾風之衣": 8,
  "獸骨之衣+": 8,
  "女神之衣": 9,
  "勇者之衣": 9,
  "不死鳥之服": 10,
  "靈魂之服": 10,
  "幻想之服": 11,
  "海洋之服": 11,
  "小刀": 1,
  "銳刃小刀": 1,
  "細刃擲刀": 2,
  "圓盤小刀": 2,
  "細直刃小刀": 3,
  "滑翔小刀": 3,
  "耳柄小刀": 4,
  "騎士小刀": 4,
  "忍者飛鏢": 5,
  "球鍔小刀": 5,
  "雙刃小刀": 5,
  "闊刃小刀": 6,
  "觸角小刀": 6,
  "兇殺刀": 7,
  "漢拉提小刀": 7,
  "切肉小刀": 8,
  "古傳小刀": 8,
  "疾速短刀+": 8,
  "手裡劍": 9,
  "華麗小刀": 9,
  "勾爪擲刀": 10,
  "幻之匕首": 10,
  "兇殘刀": 11,
  "破滅刀": 11,
  "弗旦之盾": 5,
  "弗旦之盾+": 5,
  "弗旦之袍": 5,
  "弗旦之袍+": 5,
  "弗旦衣": 5,
  "弗旦帽": 5,
  "弗旦帽+": 5,
  "弗旦鞋": 5,
  "弗旦鞋+": 5,
  "弗旦頭盔": 5,
  "弗旦頭盔+": 5,
  "弗旦鎧": 5,
  "弗旦鎧+": 5,
  "麻布帽": 1,
  "硬帽": 1,
  "皮帽": 2,
  "輕帽": 2,
  "可愛的帽子": 3,
  "硬皮帽": 3,
  "時髦帽子": 4,
  "鴨舌帽": 4,
  "高級帽子": 5,
  "劍客帽": 5,
  "藍徽章之帽": 5,
  "青銅帽子": 6,
  "裝飾著花的帽子": 6,
  "可愛的扁帽子": 8,
  "軍帽": 8,
  "時髦避暑帽": 8,
  "頭目帽子": 8,
  "羽毛帽": 9,
  "魔術師之帽": 9,
  "妖精之帽": 10,
  "黃昏之帽": 10,
  "貝斯神帽": 11,
  "神官帽": 11,
  "受詛咒的薑餅人": 1,
  "硬皮頭盔": 1,
  "銅製頭盔": 1,
  "銅鐵皮盔": 2,
  "鐵板布盔": 2,
  "金屬護額": 3,
  "鐵製頭盔": 3,
  "角飾頭盔": 4,
  "霸葛頭盔": 4,
  "開放式頭盔": 5,
  "聖騎士之盔": 5,
  "葛理克頭盔": 5,
  "巴比克頭盔": 6,
  "利刃頭盔": 6,
  "鋼製頭盔": 7,
  "騎士頭盔": 7,
  "博流蓋爾頭盔": 8,
  "鉚釘頭盔": 8,
  "鋼製頭盔+": 8,
  "羽毛頭盔": 9,
  "龍盔": 9,
  "白金頭盔": 10,
  "聖龍頭盔": 10,
  "正義頭盔": 11,
  "靈力頭盔": 11,
  "屈原的戒指": 1,
  "聖域星戒": 1,
  "弗旦之戒": 5,
  "弗旦之戒+": 5,
  "羽毛袍": 1,
  "輕皮袍": 1,
  "風袍": 2,
  "網袍": 2,
  "硬皮袍": 3,
  "環袍": 3,
  "月亮之袍": 4,
  "狐皮披風": 4,
  "烏鴉之袍": 4,
  "東方法衣": 5,
  "治癒之袍": 5,
  "聖堂之袍": 5,
  "聖者之袍": 6,
  "戰鬥長袍": 6,
  "冠軍之袍": 7,
  "時之袍": 7,
  "死神之袍": 8,
  "勇者之袍": 8,
  "潔淨之袍+": 8,
  "黑暗之袍": 9,
  "靈魂之袍": 10,
  "共鳴之袍": 11,
  "和平之袍": 11,
  "小型盾": 1,
  "小圓盾": 1,
  "板盾": 2,
  "鳶盾": 2,
  "哥特盾": 3,
  "漩渦重盾": 3,
  "士兵盾": 4,
  "重盾": 4,
  "反光之盾": 5,
  "聖者之盾": 5,
  "蜥蝪盾": 5,
  "風之盾": 6,
  "獅子盾": 6,
  "防守之盾": 7,
  "黃金之盾": 7,
  "力量之盾": 8,
  "防御之盾+": 8,
  "鏡之盾": 8,
  "火龍之盾": 9,
  "漆黑之盾": 9,
  "黑暗之盾": 10,
  "突猛盾": 11,
  "重型防禦盾": 11,
  "馬車鞋": 1,
  "運動鞋": 1,
  "皮鞋": 2,
  "安全鞋": 2,
  "光之鞋": 3,
  "戰鞋": 3,
  "薄板鞋": 4,
  "鎖鏈鞋": 4,
  "特製舞鞋": 5,
  "維京鞋": 5,
  "蜥蝪鞋": 5,
  "戰鬥鞋": 6,
  "騎士鞋": 6,
  "妖精鞋": 7,
  "紫水晶鞋": 7,
  "白金鞋": 8,
  "妖精鞋+": 8,
  "精緻高根鞋": 8,
  "神秘之鞋": 9,
  "黃金鞋": 10,
  "龍之鞋": 10,
  "大木屐": 11,
  "守護之鞋": 11,
  "攻城槍": 1,
  "短矛": 1,
  "刺槍": 2,
  "金屬槍": 2,
  "長柄尖槍": 3,
  "長柄彎槍": 3,
  "穗槍": 4,
  "雙叉戟": 4,
  "偃月刀": 5,
  "騎士槍": 5,
  "護衛槍": 5,
  "大砍槍": 6,
  "長尖槍": 6,
  "雙刃槍": 7,
  "蠍槍": 7,
  "東方長刺鎗": 8,
  "闊刃槍": 8,
  "蠍槍+": 8,
  "原始槍": 9,
  "鉤爪槍": 9,
  "三叉戰戟": 10,
  "異型槍": 10,
  "穿刺槍": 11,
  "痛擊槍": 11,
  "短杖": 1,
  "權杖": 1,
  "大地之杖": 2,
  "激流權杖": 2,
  "魔之手杖": 3,
  "魔之權杖": 3,
  "賢者手杖": 4,
  "賢者權杖": 4,
  "琥珀杖": 5,
  "琥珀權杖": 5,
  "魔晶之杖": 5,
  "元素之杖": 6,
  "神聖之杖": 6,
  "怒音之杖": 7,
  "隱者之杖": 7,
  "光明短杖": 8,
  "惡魔之杖": 8,
  "落雷權杖+": 8,
  "天使之杖": 9,
  "太陽短杖": 9,
  "星屑短杖": 10,
  "聖者之杖": 10,
  "王者之手": 11,
  "星錘杖": 11,
  "長劍": 1,
  "闊劍": 1,
  "火舌劍": 2,
  "突刺劍": 2,
  "雙手劍": 3,
  "麵包劍": 3,
  "鎖刃劍": 4,
  "雙刃長劍": 4,
  "長鍔劍": 5,
  "格鬥劍": 5,
  "黑作太刀": 5,
  "豬牙劍": 6,
  "雙刃闊劍": 6,
  "巨劍": 7,
  "長軍刀": 7,
  "長軍刀+": 8,
  "細柄短劍": 8,
  "護身短劍": 8,
  "細刃重劍": 9,
  "青龍刀": 10,
  "剛毅": 11,
  "彎勾劍": 11,
  "水龍之弓": 7,
  "水龍之斧": 7,
  "水龍之服": 7,
  "水龍之盾": 7,
  "水龍之帽": 7,
  "水龍之靴": 7,
  "水龍之槍": 7,
  "水龍之鞋": 7,
  "水龍的小刀": 7,
  "冰龍": 7
};

export const EQUIPMENT_DATA_VERSION = "20260802";
